/**
 * EventDelivery Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/integration-interoperability.schemas";

/**
 * Entity: EventDeliveryEntity
 * Description: Represents the EventDelivery domain model.
 * Source: schemas.EventDelivery
 */
export const ZEventDeliveryEntitySchema = schemas.EventDelivery as ZodType<any, any, any>;
export type EventDeliveryEntity = z.infer<typeof ZEventDeliveryEntitySchema>;
