/**
 * Connection Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodTypeAny } from "zod";
import { schemas } from "../../../schemas/integration-interoperability.schemas.js";

/**
 * Entity: ConnectionEntity
 * Description: Represents the Connection domain model.
 * Source: schemas.Connection
 */
export const ZConnectionEntitySchema = schemas.Connection as ZodTypeAny;
export type ConnectionEntity = z.infer<typeof ZConnectionEntitySchema>;
