/**
 * Routes for decisionPolicyThresholdProfiles
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/decision-intelligence.dependencies.js";
import { listDecisionPolicyThresholdProfiles } from "@cuur-cde/core/decision-intelligence/handlers/index.js";
export async function decisionPolicyThresholdProfilesRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /decision-policies/{id}/threshold-profiles
  fastify.get("/decision-policies/:id/threshold-profiles", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listDecisionPolicyThresholdProfiles(deps.decisionPolicyThresholdProfileRepo, orgId);
    return reply.code(200).send(result);
  });

}
