/**
 * Routes for explanations
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/decision-intelligence.dependencies.js";
import { createExplanation, getExplanation, listExplanations } from "@cuur-cde/core/decision-intelligence/handlers/index.js";
import type { ExplanationInput } from "@cuur-cde/core/decision-intelligence/types/index.js";
import { extractOrgId } from "../extract-org-id.js";
export async function explanationsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /explanations
  fastify.get("/explanations", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listExplanations(deps.explanationRepo, orgId, request.query || {});
    return reply.code(200).send(result);
  });
  // POST /explanations
  fastify.post("/explanations", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await createExplanation(deps.explanationRepo, orgId, request.body as ExplanationInput);
    return reply.code(201).send(result);
  });
  // GET /explanations/{id}
  fastify.get("/explanations/:id", async (request, reply) => {
    const orgId = extractOrgId(request);
        const id = (request.params as any).id;
    const result = await getExplanation(deps.explanationRepo, orgId, id);
    return reply.code(200).send(result);
  });

}
