/**
 * ModelVersion schemas
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

// Auto-generated barrel export
export * from "./entity/model-version.entity";
export * from "./dto/list-model-version.dto";
export * from "./dto/get-model-version.dto";
export * from "./dto/delete-model-version.dto";
