/**
 * List RiskAssessmentExplanation DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListRiskAssessmentExplanationParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /risk-assessment-explanation
 */
export const ZListRiskAssessmentExplanationParamsSchema = z.object({

});

export type ListRiskAssessmentExplanationParams = z.infer<typeof ZListRiskAssessmentExplanationParamsSchema>;
