/**
 * List ChecklistInstance DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListChecklistInstanceParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /checklist-instance
 */
export const ZListChecklistInstanceParamsSchema = z.object({
  patientId: z.string(),
  checklistTemplateId: z.string(),
  status: z.enum(["in-progress", "completed", "cancelled"]),
});

export type ListChecklistInstanceParams = z.infer<typeof ZListChecklistInstanceParamsSchema>;
