/**
 * PatientClinicalData Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListDiagnosticReportObservationParams, ZListDiagnosticReportObservationParamsSchema } from "@cuur-cde/core/patient-clinical-data/models/diagnostic-report-observation/index.js";
import { z } from "zod";

export function createListDiagnosticReportObservationParams(overrides: Partial<ListDiagnosticReportObservationParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListDiagnosticReportObservationParamsSchema.parse(raw);
}
