/**
 * DAO adapter for InterfaceErrorRepository
 *
 * Generated by Adapter Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  InterfaceErrorInput,
  InterfaceErrorUpdate,
  OrgId,
  PaginatedResult,
  PaginationParams,
} from "@cuur/core";
import type {
  InterfaceErrorRepository,
} from "@cuur/core/integration-interoperability/repositories/index.js";
import type {
  Timestamps,
} from "@cuur/core/integration-interoperability/types/index.js";
import type { DaoClient } from "../shared/dao-client.js";
import { NotFoundError, TransactionManager, handleDatabaseError } from "../shared/index.js";

const DEFAULT_LIMIT = 50;

export class DaoInterfaceErrorRepository implements InterfaceErrorRepository {
  private transactionManager: TransactionManager;

  constructor(private readonly dao: DaoClient) {
    this.transactionManager = new TransactionManager(dao);
  }

  async list(
    orgId: OrgId,
    params?: PaginationParams
  ): Promise<PaginatedResult<InterfaceError>> {
    try {
      const limit = params?.limit ?? DEFAULT_LIMIT;

      const records = await this.dao.interfaceError.findMany({
        where: {
          orgId,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
        orderBy: { createdAt: "desc" },
        take: limit,
        ...(params?.cursor ? {
          skip: 1,
          cursor: { id: params.cursor },
        } : {}),
      });

      return {
        items: records.map((r) => this.toDomain(r)),
        nextCursor: records.length === limit
          ? records[records.length - 1]?.id
          : undefined,
        prevCursor: undefined,
      };
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async findById(orgId: OrgId, id: string): Promise<InterfaceError | null> {
    try {
      const record = await this.dao.interfaceError.findFirst({
        where: {
          orgId,
          id,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
      });
      return record ? this.toDomain(record) : null;
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async get(orgId: OrgId, id: string): Promise<InterfaceError | null> {
    const result = await this.findById(orgId, id);
    if (!result) {
      throw new NotFoundError("InterfaceError", id);
    }
    return result;
  }
  async create(orgId: OrgId, data: InterfaceError): Promise<InterfaceError> {
    // Note: Repository interface expects InterfaceError, but we only use input fields
    // Extract only the input fields to avoid including id, createdAt, updatedAt
    const inputData = data as unknown as InterfaceErrorInput;
    try
    // Note: Repository interface expects InterfaceError, but we only use input fields
    // Extract only the input fields to avoid including id, createdAt, updatedAt
    const inputData = data as unknown as InterfaceErrorInput;
    try
    try {
      const record = await this.dao.interfaceError.create({
        data: {
          ...inputData,
          orgId, // Set orgId after spread to ensure it's always set correctly
          
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async update(orgId: OrgId, id: string, data: InterfaceErrorUpdate): Promise<InterfaceError> {
    try {
      const record = await this.dao.interfaceError.update({
        where: { id },
        data: {
          ...inputData,
          
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async createMany(orgId: OrgId, items: Array<InterfaceErrorInput>): Promise<InterfaceError[]> {
    try {
      // Use createMany for better performance
      await this.dao.interfaceError.createMany({
        data: items.map(item => ({
          ...item,
          orgId,
        })),
        skipDuplicates: true,
      });

      // Fetch created records
      const ids = items.map(item => item.id).filter(Boolean) as string[];
      if (ids.length === 0) {
        return [];
      }

      const records = await this.dao.interfaceError.findMany({
        where: { id: { in: ids }, orgId },
      });

      return records.map((r) => this.toDomain(r));
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async updateMany(orgId: OrgId, updates: Array<{ id: string; data: InterfaceErrorUpdate }>): Promise<InterfaceError[]> {
    try {
      // Use transaction for atomic batch updates
      return await this.transactionManager.execute(orgId, async (tx) => {
        const results: InterfaceError[] = [];
        for (const { id, data } of updates) {
          const record = await tx.interfaceError.update({
            where: { id },
            data,
          });
          results.push(this.toDomain(record));
        }
        return results;
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  private toDomain(model: any): InterfaceError {
    return {
      ...model,
      createdAt: model.createdAt instanceof Date
        ? model.createdAt
        : new Date(model.createdAt),
      updatedAt: model.updatedAt instanceof Date
        ? model.updatedAt
        : model.updatedAt ? new Date(model.updatedAt) : undefined,
    } as InterfaceError;
  }
}
