/**
 * DAO adapter for IntegrationRunRepository
 *
 * Generated by Adapter Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  OrgId,
  PaginatedResult,
  PaginationParams,
} from "@cuur/core";
import type {
  IntegrationRunRepository,
} from "@cuur/core/integration-interoperability/repositories/index.js";
import type {
  IntegrationRunInput,
  Timestamps,
} from "@cuur/core/integration-interoperability/types/index.js";
import type { DaoClient } from "../shared/dao-client.js";
import { NotFoundError, TransactionManager, handleDatabaseError } from "../shared/index.js";

const DEFAULT_LIMIT = 50;

export class DaoIntegrationRunRepository implements IntegrationRunRepository {
  private transactionManager: TransactionManager;

  constructor(private readonly dao: DaoClient) {
    this.transactionManager = new TransactionManager(dao);
  }

  async list(
    orgId: OrgId,
    params?: PaginationParams
  ): Promise<PaginatedResult<Timestamps>> {
    try {
      const limit = params?.limit ?? DEFAULT_LIMIT;

      const records = await this.dao.integrationRun.findMany({
        where: {
          orgId,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
        orderBy: { createdAt: "desc" },
        take: limit,
        ...(params?.cursor ? {
          skip: 1,
          cursor: { id: params.cursor },
        } : {}),
      });

      return {
        items: records.map((r) => this.toDomain(r)),
        nextCursor: records.length === limit
          ? records[records.length - 1]?.id
          : undefined,
        prevCursor: undefined,
      };
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async findById(orgId: OrgId, id: string): Promise<Timestamps | null> {
    try {
      const record = await this.dao.integrationRun.findFirst({
        where: {
          orgId,
          id,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
      });
      return record ? this.toDomain(record) : null;
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async get(orgId: OrgId, id: string): Promise<Timestamps | null> {
    const result = await this.findById(orgId, id);
    if (!result) {
      throw new NotFoundError("Timestamps", id);
    }
    return result;
  }
  async create(orgId: OrgId, data: IntegrationRunInput, createdBy?: string): Promise<Timestamps> {
    try {
      const record = await this.dao.integrationRun.create({
        data: {
          ...data,
          orgId, // Set orgId after spread to ensure it's always set correctly
          createdBy: createdBy ?? null, // Audit trail
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async createMany(orgId: OrgId, items: Array<IntegrationRunInput>): Promise<Timestamps[]> {
    try {
      // Use createMany for better performance
      await this.dao.integrationRun.createMany({
        data: items.map(item => ({
          ...item,
          orgId,
        })),
        skipDuplicates: true,
      });

      // Fetch created records
      const ids = items.map(item => item.id).filter(Boolean) as string[];
      if (ids.length === 0) {
        return [];
      }

      const records = await this.dao.integrationRun.findMany({
        where: { id: { in: ids }, orgId },
      });

      return records.map((r) => this.toDomain(r));
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  private toDomain(model: any): Timestamps {
    return {
      ...model,
      createdAt: model.createdAt instanceof Date
        ? model.createdAt
        : new Date(model.createdAt),
      updatedAt: model.updatedAt instanceof Date
        ? model.updatedAt
        : model.updatedAt ? new Date(model.updatedAt) : undefined,
    } as Timestamps;
  }
}
