/**
 * Routes for modelVersionTests
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import { extractOrgId } from "../context/org-context.js";
import type { Dependencies } from "../dependencies/knowledge-evidence.dependencies.js";
import { listModelVersionTests } from "@cuur-cde/core/knowledge-evidence/handlers/index.js";
export async function modelVersionTestsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /model-versions/{id}/tests (nested route)
  fastify.get("/model-versions/:id/tests", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listModelVersionTests(deps.modelVersionTestRepo, orgId);
    return reply.code(200).send(result);
  });

  // GET /model-version-tests (flat route for dashboard)
  fastify.get("/model-version-tests", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listModelVersionTests(deps.modelVersionTestRepo, orgId);
    return reply.code(200).send(result);
  });

}
