/**
 * Routes for modelVersionFeatureDefinitions
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/knowledge-evidence.dependencies.js";
import { listModelVersionFeatureDefinitions } from "@cuur/core/knowledge-evidence/handlers/index.js";
export async function modelVersionFeatureDefinitionsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /model-versions/{id}/feature-definitions
  fastify.get("/model-versions/:id/feature-definitions", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listModelVersionFeatureDefinitions(deps.modelVersionFeatureDefinitionRepo, orgId);
    return reply.code(200).send(result);
  });

}
