/**
 * Routes for modelDefinitionVersions
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import { extractOrgId } from "../extract-org-id.js";
import type { Dependencies } from "../dependencies/knowledge-evidence.dependencies.js";
import { listModelDefinitionVersions } from "@cuur-cde/core/knowledge-evidence/handlers/index.js";
export async function modelDefinitionVersionsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /model-definitions/{id}/versions
  fastify.get("/model-definitions/:id/versions", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listModelDefinitionVersions(deps.modelDefinitionVersionRepo, orgId);
    return reply.code(200).send(result);
  });

}
