/**
 * Create DataImportBatch DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/integration-interoperability.schemas";

/**
 * DTO: DataImportBatchInput
 * Direction: Request Body → Handler → Domain
 * Route: Create data import batch
 * OpenAPI Source: schemas.DataImportBatchInput
 */
export const ZDataImportBatchInputSchema = schemas.DataImportBatchInput;
export type DataImportBatchInput = z.infer<typeof ZDataImportBatchInputSchema>;
