/**
 * Update DataImportBatch DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/integration-interoperability.schemas";

/**
 * DTO: DataImportBatchUpdate
 * Direction: Request Body → Handler → Domain
 * Route: Update data import batch
 * OpenAPI Source: schemas.DataImportBatchUpdate
 */
export const ZDataImportBatchUpdateSchema = schemas.DataImportBatchUpdate;
export type DataImportBatchUpdate = z.infer<typeof ZDataImportBatchUpdateSchema>;
