/**
 * EpisodeOfCareEncounter Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodTypeAny } from "zod";
import { schemas } from "../../../schemas/workflow-care-pathways.schemas.js";

/**
 * Entity: EpisodeOfCareEncounterEntity
 * Description: Represents the EpisodeOfCareEncounter domain model.
 * Source: schemas.EpisodeOfCareEncounter
 */
export const ZEpisodeOfCareEncounterEntitySchema = schemas.EpisodeOfCareEncounter as ZodTypeAny;
export type EpisodeOfCareEncounterEntity = z.infer<typeof ZEpisodeOfCareEncounterEntitySchema>;
