/**
 * ModelDefinitionPerformanceMetric Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas";

/**
 * Entity: ModelDefinitionPerformanceMetricEntity
 * Description: Represents the ModelDefinitionPerformanceMetric domain model.
 * Source: schemas.ModelDefinitionPerformanceMetric
 */
export const ZModelDefinitionPerformanceMetricEntitySchema = schemas.ModelDefinitionPerformanceMetric;
export type ModelDefinitionPerformanceMetricEntity = z.infer<typeof ZModelDefinitionPerformanceMetricEntitySchema>;
