/**
 * Connection schemas
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

// Auto-generated barrel export
export * from "./entity/connection.entity";
export * from "./dto/list-connection.dto";
export * from "./dto/create-connection.dto";
export * from "./dto/get-connection.dto";
export * from "./dto/update-connection.dto";
export * from "./dto/delete-connection.dto";
