/**
 * Get Guideline DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetGuidelinePath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get clinical guideline by ID
 */
export const ZGetGuidelinePathSchema = z.object({
  guidelineId: z.string(),
});

export type GetGuidelinePath = z.infer<typeof ZGetGuidelinePathSchema>;
