/**
 * Get QuestionnaireTemplate DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetQuestionnaireTemplatePath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get questionnaire template by ID
 */
export const ZGetQuestionnaireTemplatePathSchema = z.object({
  questionnaireTemplateId: z.string(),
});

export type GetQuestionnaireTemplatePath = z.infer<typeof ZGetQuestionnaireTemplatePathSchema>;
