/**
 * HandoffTask Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodTypeAny } from "zod";
import { schemas } from "../../../schemas/workflow-care-pathways.schemas.js";

/**
 * Entity: HandoffTaskEntity
 * Description: Represents the HandoffTask domain model.
 * Source: schemas.HandoffTask
 */
export const ZHandoffTaskEntitySchema = schemas.HandoffTask as ZodTypeAny;
export type HandoffTaskEntity = z.infer<typeof ZHandoffTaskEntitySchema>;
