/**
 * Get ValueSet DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetValueSetPath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get value set by ID
 */
export const ZGetValueSetPathSchema = z.object({
  valueSetId: z.string(),
});

export type GetValueSetPath = z.infer<typeof ZGetValueSetPathSchema>;
