/**
 * Update ValueSet DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas";

/**
 * DTO: ValueSetUpdate
 * Direction: Request Body → Handler → Domain
 * Route: Update value set
 * OpenAPI Source: schemas.ValueSetUpdate
 */
export const ZValueSetUpdateSchema = schemas.ValueSetUpdate;
export type ValueSetUpdate = z.infer<typeof ZValueSetUpdateSchema>;
