/**
 * ClinicalRule Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "@cuur-cde/core/knowledge-evidence/schemas/knowledge-evidence.schemas";

/**
 * Entity: ClinicalRuleEntity
 * Description: Represents the ClinicalRule domain model.
 * Source: schemas.ClinicalRule
 */
export const ZClinicalRuleEntitySchema = schemas.ClinicalRule as ZodType<any, any, any>;
export type ClinicalRuleEntity = z.infer<typeof ZClinicalRuleEntitySchema>;
