/**
 * WorkQueue handlers
 *
 * Generated by Handler Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./list-work-queues.handler.js";
export * from "./create-work-queue.handler.js";
export * from "./get-work-queue.handler.js";
export * from "./update-work-queue.handler.js";
export * from "./delete-work-queue.handler.js";
