/**
 * Get DecisionRequest DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetDecisionRequestPath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get decision request by ID
 */
export const ZGetDecisionRequestPathSchema = z.object({
  decisionRequestId: z.string(),
});

export type GetDecisionRequestPath = z.infer<typeof ZGetDecisionRequestPathSchema>;
