/**
 * ValueSetCode Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas.js";

/**
 * Entity: ValueSetCodeEntity
 * Description: Represents the ValueSetCode domain model.
 * Source: schemas.ValueSetCode
 */
export const ZValueSetCodeEntitySchema = schemas.ValueSetCode as ZodType<any, any, any>;
export type ValueSetCodeEntity = z.infer<typeof ZValueSetCodeEntitySchema>;
