/**
 * ModelInvocationExplanation Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodTypeAny } from "zod";
import { schemas } from "../../../schemas/decision-intelligence.schemas.js";

/**
 * Entity: ModelInvocationExplanationEntity
 * Description: Represents the ModelInvocationExplanation domain model.
 * Source: schemas.ModelInvocationExplanation
 */
export const ZModelInvocationExplanationEntitySchema = schemas.ModelInvocationExplanation as ZodTypeAny;
export type ModelInvocationExplanationEntity = z.infer<typeof ZModelInvocationExplanationEntitySchema>;
