/**
 * ModelInvocationExplanation Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "@cuur-cde/core/decision-intelligence/schemas/decision-intelligence.schemas";

/**
 * Entity: ModelInvocationExplanationEntity
 * Description: Represents the ModelInvocationExplanation domain model.
 * Source: schemas.ModelInvocationExplanation
 */
export const ZModelInvocationExplanationEntitySchema = schemas.ModelInvocationExplanation as ZodType<any, any, any>;
export type ModelInvocationExplanationEntity = z.infer<typeof ZModelInvocationExplanationEntitySchema>;
