/**
 * Get FHIRMappingProfile DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetFHIRMappingProfilePath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get FHIR mapping profile by ID
 */
export const ZGetFHIRMappingProfilePathSchema = z.object({
  fHIRMappingProfileId: z.string(),
});

export type GetFHIRMappingProfilePath = z.infer<typeof ZGetFHIRMappingProfilePathSchema>;
