/**
 * Observation Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodTypeAny } from "zod";
import { schemas } from "../../../schemas/patient-clinical-data.schemas.js";

/**
 * Entity: ObservationEntity
 * Description: Represents the Observation domain model.
 * Source: schemas.Observation
 */
export const ZObservationEntitySchema = schemas.Observation as ZodTypeAny;
export type ObservationEntity = z.infer<typeof ZObservationEntitySchema>;
