/**
 * createDiagnosticReport Handler Tests
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * createDiagnosticReport Handler Tests
 *
 * Maps to: packages/core/src/patient-clinical-data/handlers/diagnostic-report.handler/create-diagnostic-report.handler.ts
 * Strategy: Mock repositories, handler-centric, business rules focus
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { createDiagnosticReport as createDiagnosticReportHandler } from "@cuur/core/patient-clinical-data/handlers/index.js";

import { seedFaker,
    createDiagnosticReportHandler } from "@quub/factories";

describe("createDiagnosticReport - Business Rules", () => {
  const FIXED_DATE = new Date("2025-01-01T00:00:00Z");
  const FAKER_SEED = 12345;
  const TEST_ORG_ID = "ID_01HQZX3K8PQRS7VN6M9TW1ABJZ";

  beforeEach(() => {

    vi.useFakeTimers();
    vi.setSystemTime(FIXED_DATE);
    seedFaker(FAKER_SEED);
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  describe("✅ Happy Path", () => {
    it("should create diagnosticreporthandler with valid data", async () => {
      const input = createDiagnosticReportHandler();

      const result = await createDiagnosticReportHandler(
        TEST_ORG_ID,
        input
      );

      expect(result.data).toBeDefined();
      expect(result.data?.id).toBeDefined();
      expect(result.data?.orgId).toBe(TEST_ORG_ID);
    });
  });

  describe("🔒 Org Isolation", () => {
    it("should enforce org isolation", async () => {
      const input = createDiagnosticReportHandler();

      const result = await createDiagnosticReportHandler(
        TEST_ORG_ID,
        input
      );

      expect(result.data?.orgId).toBe(TEST_ORG_ID);
    });
  });
});
