/**
 * EncounterCondition Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/patient-clinical-data.schemas";

/**
 * Entity: EncounterConditionEntity
 * Description: Represents the EncounterCondition domain model.
 * Source: schemas.EncounterCondition
 */
export const ZEncounterConditionEntitySchema = schemas.EncounterCondition as ZodType<any, any, any>;
export type EncounterConditionEntity = z.infer<typeof ZEncounterConditionEntitySchema>;
