/**
 * List OrderSetTemplate DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListOrderSetTemplateParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /order-set-template
 */
export const ZListOrderSetTemplateParamsSchema = z.object({
  category: z.string(),
  status: z.enum(["draft", "active", "deprecated"]),
});

export type ListOrderSetTemplateParams = z.infer<typeof ZListOrderSetTemplateParamsSchema>;
