/**
 * IntegrationRunError Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/integration-interoperability.schemas";

/**
 * Entity: IntegrationRunErrorEntity
 * Description: Represents the IntegrationRunError domain model.
 * Source: schemas.IntegrationRunError
 */
export const ZIntegrationRunErrorEntitySchema = schemas.IntegrationRunError;
export type IntegrationRunErrorEntity = z.infer<typeof ZIntegrationRunErrorEntitySchema>;
