/**
 * DecisionIntelligence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { DecisionRequestInput } from "@cuur/core/decision-intelligence/models/decision-request/index.js";
import { decisionintelligenceSchemas as schemas } from "@cuur/core/decision-intelligence/index.js";
import { z } from "zod";

export function createDecisionRequestInput(overrides: Partial<DecisionRequestInput> = {}) {
  const raw = {
    context: overrides.context ?? {},
    decisionSessionId: overrides.decisionSessionId ?? faker.string.alpha(10),
    metadata: overrides.metadata ?? {},
    patientId: overrides.patientId ?? faker.string.alpha(10),
    priority: overrides.priority ?? faker.helpers.arrayElement(["low", "normal", "high", "urgent"]),
    requestType: overrides.requestType ?? faker.helpers.arrayElement(["diagnostic", "treatment", "risk-assessment", "pathway-selection"]),
    ...overrides,
  };

  return schemas.DecisionRequestInput.parse(raw);
}
