/**
 * WorkflowInstanceTask Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "@cuur-cde/core/workflow-care-pathways/schemas/workflow-care-pathways.schemas";

/**
 * Entity: WorkflowInstanceTaskEntity
 * Description: Represents the WorkflowInstanceTask domain model.
 * Source: schemas.WorkflowInstanceTask
 */
export const ZWorkflowInstanceTaskEntitySchema = schemas.WorkflowInstanceTask as ZodType<any, any, any>;
export type WorkflowInstanceTaskEntity = z.infer<typeof ZWorkflowInstanceTaskEntitySchema>;
