/**
 * KnowledgeEvidence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListQuestionnaireTemplateQuestionParams, ZListQuestionnaireTemplateQuestionParamsSchema } from "@cuur/core/knowledge-evidence/models/questionnaire-template-question/index.js";
import { z } from "zod";

export function createListQuestionnaireTemplateQuestionParams(overrides: Partial<ListQuestionnaireTemplateQuestionParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListQuestionnaireTemplateQuestionParamsSchema.parse(raw);
}
