/**
 * Get ExternalSystem DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetExternalSystemPath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get external system by ID
 */
export const ZGetExternalSystemPathSchema = z.object({
  externalSystemId: z.string(),
});

export type GetExternalSystemPath = z.infer<typeof ZGetExternalSystemPathSchema>;
