packages:
  # Core root package (@cuur-cde/core)
  - "packages/core"
  # Shared database package (@cde/db)
  - "packages/database"
  # Core domain packages
  - "packages/core/_shared"
  - "packages/core/decision-intelligence"
  - "packages/core/integration-interoperability"
  - "packages/core/knowledge-evidence"
  - "packages/core/patient-clinical-data"
  - "packages/core/workflow-care-pathways"
  # Adapter packages
  - "platform/adapters/_shared"
  - "platform/adapters/decision-intelligence"
  - "platform/adapters/integration-interoperability"
  - "platform/adapters/knowledge-evidence"
  - "platform/adapters/patient-clinical-data"
  - "platform/adapters/workflow-care-pathways"
  # Service packages
  - "platform/services/decision-intelligence"
  - "platform/services/integration-interoperability"
  - "platform/services/knowledge-evidence"
  - "platform/services/patient-clinical-data"
  - "platform/services/workflow-care-pathways"
  # Test packages
  - "platform/tests/decision-intelligence"
  - "platform/tests/integration-interoperability"
  - "platform/tests/knowledge-evidence"
  - "platform/tests/patient-clinical-data"
  - "platform/tests/workflow-care-pathways"
