/**
 * DAO adapter for DataExportBatchRepository
 *
 * Generated by Adapter Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { OrgId, PaginatedResult, PaginationParams } from "@cuur/adapters-shared";
import type { DataExportBatchRepository } from "@cuur-cde/core/integration-interoperability/repositories/index.js";
import type { UpdateDataExportBatchRequest } from "@cuur-cde/core/integration-interoperability/types/index.js";
import type {
  DataExportBatchInput,
  DataExportBatchUpdate,
  DataExportBatch,
  Timestamps,
} from "@cuur-cde/core/integration-interoperability/types/index.js";
import type { DaoClient } from "../../_shared/src/dao-client.js";
import { NotFoundError, TransactionManager, handleDatabaseError } from "@cuur/adapters-shared";

const DEFAULT_LIMIT = 50;

export class DaoDataExportBatchRepository implements DataExportBatchRepository {
  private transactionManager: TransactionManager;

  constructor(private readonly dao: DaoClient) {
    this.transactionManager = new TransactionManager(dao);
  }

  async list(orgId: OrgId, params?: PaginationParams): Promise<PaginatedResult<DataExportBatch>> {
    try {
      const limit = params?.limit ?? DEFAULT_LIMIT;

      const records = await this.dao.dataExportBatchInput.findMany({
        where: {
          orgId,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
        orderBy: { createdAt: "desc" },
        take: limit,
        ...(params && "cursor" in params && params.cursor
          ? {
              skip: 1,
              cursor: { id: params.cursor },
            }
          : {}),
      });

      return {
        items: records.map((r: any) => this.toDomain(r)),
        nextCursor: records.length === limit ? records[records.length - 1]?.id : undefined,
        prevCursor: undefined,
      };
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async findById(orgId: OrgId, id: string): Promise<DataExportBatch | null> {
    try {
      const record = await this.dao.dataExportBatchInput.findFirst({
        where: {
          orgId,
          id,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
      });
      return record ? this.toDomain(record) : null;
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async get(orgId: OrgId, id: string): Promise<DataExportBatch | null> {
    const result = await this.findById(orgId, id);
    if (!result) {
      throw new NotFoundError("DataExportBatch", id);
    }
    return result;
  }
  async create(orgId: OrgId, data: DataExportBatch): Promise<DataExportBatch> {
    // Note: Repository interface expects DataExportBatch, but we only use input fields
    // Extract only the input fields to avoid including id, createdAt, updatedAt
    const inputData = data as unknown as DataExportBatchInput;
    try {
      const record = await this.dao.dataExportBatchInput.create({
        data: {
          ...data,
          orgId, // Set orgId after spread to ensure it's always set correctly
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async update(
    orgId: OrgId,
    id: string,
    data: UpdateDataExportBatchRequest
  ): Promise<DataExportBatch> {
    try {
      const record = await this.dao.dataExportBatchInput.update({
        where: { id, orgId },
        data: {
          ...data,
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async delete(orgId: OrgId, id: string): Promise<void> {
    try {
      // Soft delete: set deletedAt instead of hard delete
      await this.dao.dataExportBatchInput.update({
        where: { id, orgId },
        data: {
          deletedAt: new Date(),
        },
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async createMany(orgId: OrgId, items: Array<DataExportBatchInput>): Promise<DataExportBatch[]> {
    try {
      // Use transaction with individual creates to get created records with IDs
      return await this.transactionManager.executeInTransaction(async (tx) => {
        const results: DataExportBatch[] = [];
        for (const item of items) {
          const record = await tx.dataExportBatchInput.create({
            data: {
              ...item,
              orgId,
            },
          });
          results.push(this.toDomain(record));
        }
        return results;
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async updateMany(
    orgId: OrgId,
    updates: Array<{ id: string; data: DataExportBatchUpdate }>
  ): Promise<DataExportBatch[]> {
    try {
      // Use transaction for atomic batch updates
      return await this.transactionManager.executeInTransaction(async (tx) => {
        const results: DataExportBatch[] = [];
        for (const { id, data } of updates) {
          const record = await tx.dataExportBatchInput.update({
            where: { id, orgId },
            data,
          });
          results.push(this.toDomain(record));
        }
        return results;
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async deleteMany(orgId: OrgId, ids: string[]): Promise<void> {
    try {
      // Soft delete: set deletedAt for multiple records
      await this.dao.dataExportBatchInput.updateMany({
        where: {
          id: { in: ids },
          orgId,
        },
        data: {
          deletedAt: new Date(),
        },
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  private toDomain(model: any): DataExportBatch {
    return {
      ...model,
      createdAt: model.createdAt instanceof Date ? model.createdAt : new Date(model.createdAt),
      updatedAt:
        model.updatedAt instanceof Date
          ? model.updatedAt
          : model.updatedAt
          ? new Date(model.updatedAt)
          : undefined,
    } as DataExportBatch;
  }
}
