/**
 * DAO adapter for HL7MessageRepository
 *
 * Generated by Adapter Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { OrgId, PaginatedResult, PaginationParams } from "@cuur-cde/core/_shared";
import type { HL7MessageRepository } from "@cuur-cde/core/integration-interoperability";
import type {
  HL7MessageInput,
  HL7Message,
  Timestamps,
} from "@cuur-cde/core/integration-interoperability";
import type { DaoClient } from "../db/dao-client.js";
import { NotFoundError, TransactionManager, handleDatabaseError } from "../utils/repository-helpers.js";

const DEFAULT_LIMIT = 50;

export class DaoHL7MessageRepository implements HL7MessageRepository {
  private transactionManager: TransactionManager;

  constructor(private readonly dao: DaoClient) {
    this.transactionManager = new TransactionManager(dao);
  }

  async list(orgId: OrgId, params?: PaginationParams): Promise<PaginatedResult<HL7Message>> {
    try {
      const limit = params?.limit ?? DEFAULT_LIMIT;

      const records = await this.dao.hl7message.findMany({
        where: {
          orgId,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
        orderBy: { createdAt: "desc" },
        take: limit,
        ...(params && "cursor" in params && params.cursor
          ? {
              skip: 1,
              cursor: { id: params.cursor },
            }
          : {}),
      });

      return {
        items: records.map((r: any) => this.toDomain(r)),
        nextCursor: records.length === limit ? records[records.length - 1]?.id : undefined,
        prevCursor: undefined,
      };
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async findById(orgId: OrgId, id: string): Promise<HL7Message | null> {
    try {
      const record = await this.dao.hl7message.findFirst({
        where: {
          orgId,
          id,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
      });
      return record ? this.toDomain(record) : null;
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async get(orgId: OrgId, id: string): Promise<HL7Message | null> {
    const result = await this.findById(orgId, id);
    if (!result) {
      throw new NotFoundError("HL7Message", id);
    }
    return result;
  }
  async create(orgId: OrgId, data: HL7Message): Promise<HL7Message> {
    try {
      const record = await this.dao.hl7message.create({
        data: {
          ...data,
          orgId, // Set orgId after spread to ensure it's always set correctly
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async delete(orgId: OrgId, id: string): Promise<void> {
    try {
      // Soft delete: set deletedAt instead of hard delete
      await this.dao.hl7message.update({
        where: { id, orgId },
        data: {
          deletedAt: new Date(),
        },
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async createMany(orgId: OrgId, items: Array<HL7MessageInput>): Promise<HL7Message[]> {
    try {
      // Use transaction with individual creates to get created records with IDs
      return await this.transactionManager.executeInTransaction(async (tx) => {
        const results: HL7Message[] = [];
        for (const item of items) {
          const record = await tx.hl7message.create({
            data: {
              ...item,
              orgId,
            },
          });
          results.push(this.toDomain(record));
        }
        return results;
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async deleteMany(orgId: OrgId, ids: string[]): Promise<void> {
    try {
      // Soft delete: set deletedAt for multiple records
      await this.dao.hl7message.updateMany({
        where: {
          id: { in: ids },
          orgId,
        },
        data: {
          deletedAt: new Date(),
        },
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  private toDomain(model: any): HL7Message {
    return {
      ...model,
      createdAt: model.createdAt instanceof Date ? model.createdAt : new Date(model.createdAt),
      updatedAt:
        model.updatedAt instanceof Date
          ? model.updatedAt
          : model.updatedAt
          ? new Date(model.updatedAt)
          : undefined,
    } as HL7Message;
  }
}
