/**
 * CarePlanChecklist Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/workflow-care-pathways.schemas";

/**
 * Entity: CarePlanChecklistEntity
 * Description: Represents the CarePlanChecklist domain model.
 * Source: schemas.CarePlanChecklist
 */
export const ZCarePlanChecklistEntitySchema = schemas.CarePlanChecklist;
export type CarePlanChecklistEntity = z.infer<typeof ZCarePlanChecklistEntitySchema>;
