/**
 * ConceptMapMapping Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas";

/**
 * Entity: ConceptMapMappingEntity
 * Description: Represents the ConceptMapMapping domain model.
 * Source: schemas.ConceptMapMapping
 */
export const ZConceptMapMappingEntitySchema = schemas.ConceptMapMapping as ZodType<any, any, any>;
export type ConceptMapMappingEntity = z.infer<typeof ZConceptMapMappingEntitySchema>;
