/**
 * List Handoff DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListHandoffParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /handoff
 */
export const ZListHandoffParamsSchema = z.object({
  patientId: z.string(),
  fromTeam: z.string(),
  toTeam: z.string(),
});

export type ListHandoffParams = z.infer<typeof ZListHandoffParamsSchema>;
