/**
 * List ModelInvocationExplanation DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListModelInvocationExplanationParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /model-invocation-explanation
 */
export const ZListModelInvocationExplanationParamsSchema = z.object({

});

export type ListModelInvocationExplanationParams = z.infer<typeof ZListModelInvocationExplanationParamsSchema>;
