/**
 * listRecommendationExplanations Handler Tests
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * listRecommendationExplanations Handler Tests
 *
 * Maps to: packages/core/src/decision-intelligence/handlers/recommendation-explanations.handler/list-recommendation-explanations.handler.ts
 * Strategy: Mock repositories, handler-centric, business rules focus
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { listRecommendationExplanations as listRecommendationExplanationsHandler } from "@cuur/core/decision-intelligence/handlers/index.js";

import { seedFaker,
    createRecommendationExplanationsHandler } from "@quub/factories";

describe("listRecommendationExplanations - Business Rules", () => {
  const FIXED_DATE = new Date("2025-01-01T00:00:00Z");
  const FAKER_SEED = 12345;
  const TEST_ORG_ID = "ID_01HQZX3K8PQRS7VN6M9TW1ABJZ";

  beforeEach(() => {

    vi.useFakeTimers();
    vi.setSystemTime(FIXED_DATE);
    seedFaker(FAKER_SEED);
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  describe("✅ Happy Path", () => {
    it("should list recommendationexplanationshandlers", async () => {
      const result = await listRecommendationExplanationsHandler(TEST_ORG_ID);

      expect(result.data).toBeDefined();
      expect(Array.isArray(result.data)).toBe(true);
    });
  });
});
