/**
 * Routes for decisionRequestExplanations
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/decision-intelligence.dependencies.js";
import { listDecisionRequestExplanations } from "@cuur/core/decision-intelligence/handlers/index.js";
export async function decisionRequestExplanationsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /decision-requests/{id}/explanations
  fastify.get("/decision-requests/:id/explanations", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listDecisionRequestExplanations(deps.decisionRequestExplanationRepo, orgId);
    return reply.code(200).send(result);
  });

}
