/**
 * Routes for modelInvocationExplanations
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/decision-intelligence.dependencies.js";
import { listModelInvocationExplanations } from "@cuur/core/decision-intelligence/handlers/index.js";
export async function modelInvocationExplanationsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /model-invocations/{id}/explanations
  fastify.get("/model-invocations/:id/explanations", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listModelInvocationExplanations(deps.modelInvocationExplanationRepo, orgId);
    return reply.code(200).send(result);
  });

}
