/**
 * ModelVersionFeatureDefinition Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas";

/**
 * Entity: ModelVersionFeatureDefinitionEntity
 * Description: Represents the ModelVersionFeatureDefinition domain model.
 * Source: schemas.ModelVersionFeatureDefinition
 */
export const ZModelVersionFeatureDefinitionEntitySchema = schemas.ModelVersionFeatureDefinition;
export type ModelVersionFeatureDefinitionEntity = z.infer<typeof ZModelVersionFeatureDefinitionEntitySchema>;
