/**
 * Get Condition DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetConditionPath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get condition by ID
 */
export const ZGetConditionPathSchema = z.object({
  conditionId: z.string(),
});

export type GetConditionPath = z.infer<typeof ZGetConditionPathSchema>;
