/**
 * Get KnowledgePackage DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetKnowledgePackagePath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get knowledge package by ID
 */
export const ZGetKnowledgePackagePathSchema = z.object({
  knowledgePackageId: z.string(),
});

export type GetKnowledgePackagePath = z.infer<typeof ZGetKnowledgePackagePathSchema>;
