/**
 * Update CareTeam DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/patient-clinical-data.schemas";

/**
 * DTO: CareTeamUpdate
 * Direction: Request Body → Handler → Domain
 * Route: Update care team
 * OpenAPI Source: schemas.CareTeamUpdate
 */
export const ZCareTeamUpdateSchema = schemas.CareTeamUpdate;
export type CareTeamUpdate = z.infer<typeof ZCareTeamUpdateSchema>;
