/**
 * Routes for orderSetTemplateItems
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/knowledge-evidence.dependencies.js";
import { listOrderSetTemplateItems } from "@cuur/core/knowledge-evidence/handlers/index.js";
export async function orderSetTemplateItemsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /order-set-templates/{id}/items
  fastify.get("/order-set-templates/:id/items", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await listOrderSetTemplateItems(deps.orderSetTemplateItemRepo, orgId);
    return reply.code(200).send(result);
  });

}
