/**
 * Repository interface for ClinicalRule
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  ClinicalRule,
  ListClinicalRulesParams,
  UpdateClinicalRuleRequest
} from "../types/index.js";
/**
 * ClinicalRuleRepository Interface
 */
export interface ClinicalRuleRepository extends CrudRepository<ClinicalRule, ClinicalRule, UpdateClinicalRuleRequest, string, ListClinicalRulesParams> {

}
