/**
 * Repository interface for EvidenceCitation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  EvidenceCitation,
  ListEvidenceCitationsParams,
  UpdateEvidenceCitationRequest
} from "../types/index.js";
/**
 * EvidenceCitationRepository Interface
 */
export interface EvidenceCitationRepository extends CrudRepository<EvidenceCitation, EvidenceCitation, UpdateEvidenceCitationRequest, string, ListEvidenceCitationsParams> {

}
