/**
 * Repository interface for GuidelineEvidenceCitation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  GuidelineEvidenceCitation
} from "../types/index.js";
/**
 * GuidelineEvidenceCitationRepository Interface
 */
export interface GuidelineEvidenceCitationRepository extends ReadRepository<GuidelineEvidenceCitation, string, Record<string, never>> {

}
