/**
 * Repository interface for ModelDefinition
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  Timestamps,
  ListModelDefinitionsParams,
  ModelDefinitionInput,
  ModelDefinitionUpdate
} from "../types/index.js";
/**
 * ModelDefinitionRepository Interface
 */
export interface ModelDefinitionRepository extends CrudRepository<Timestamps, ModelDefinitionInput, ModelDefinitionUpdate, string, ListModelDefinitionsParams> {

}
