/**
 * Repository interface for OntologyTerm
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  OntologyTerm,
  SearchOntologyTermsParams
} from "../types/index.js";
/**
 * OntologyTermRepository Interface
 */
export interface OntologyTermRepository extends ReadRepository<OntologyTerm, string, SearchOntologyTermsParams> {

}
