/**
 * List CareProtocolOrderSet DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListCareProtocolOrderSetParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /care-protocol-order-set
 */
export const ZListCareProtocolOrderSetParamsSchema = z.object({

});

export type ListCareProtocolOrderSetParams = z.infer<typeof ZListCareProtocolOrderSetParamsSchema>;
