/**
 * DecisionIntelligence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { GetSimulationRunPath, ZGetSimulationRunPathSchema } from "@cuur-cde/core/decision-intelligence/models/simulation-run/index.js";
import { z } from "zod";

export function createGetSimulationRunPath(overrides: Partial<GetSimulationRunPath> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZGetSimulationRunPathSchema.parse(raw);
}
