/**
 * InterfaceHealthCheck Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/integration-interoperability.schemas";

/**
 * Entity: InterfaceHealthCheckEntity
 * Description: Represents the InterfaceHealthCheck domain model.
 * Source: schemas.InterfaceHealthCheck
 */
export const ZInterfaceHealthCheckEntitySchema = schemas.InterfaceHealthCheck;
export type InterfaceHealthCheckEntity = z.infer<typeof ZInterfaceHealthCheckEntitySchema>;
