/**
 * Create Recommendation DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/decision-intelligence.schemas";

/**
 * DTO: RecommendationInput
 * Direction: Request Body → Handler → Domain
 * Route: Create recommendation
 * OpenAPI Source: schemas.RecommendationInput
 */
export const ZRecommendationInputSchema = schemas.RecommendationInput;
export type RecommendationInput = z.infer<typeof ZRecommendationInputSchema>;
