/**
 * IntegrationRun Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/integration-interoperability.schemas.js";

/**
 * Entity: IntegrationRunEntity
 * Description: Represents the IntegrationRun domain model.
 * Source: schemas.IntegrationRun
 */
export const ZIntegrationRunEntitySchema = schemas.IntegrationRun as ZodType<any, any, any>;
export type IntegrationRunEntity = z.infer<typeof ZIntegrationRunEntitySchema>;
