/**
 * PatientClinicalData Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ClinicalNoteUpdate } from "@cuur-cde/core/patient-clinical-data";
import { patientclinicaldataSchemas as schemas } from "@cuur-cde/core/patient-clinical-data/index.js";
import { z } from "zod";

export function createClinicalNoteUpdate(overrides: Partial<ClinicalNoteUpdate> = {}) {
  const raw = {
    content: overrides.content ?? faker.string.alpha(10),
    noteType: overrides.noteType ?? faker.helpers.arrayElement(["history-physical", "progress", "discharge", "consultation", "procedure", "other"]),
    title: overrides.title ?? faker.string.alpha(10),
    ...overrides,
  };

  return schemas.ClinicalNoteUpdate.parse(raw);
}
