/**
 * PatientClinicalData Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { DeleteDocument, ZDeleteDocumentSchema } from "@cuur-cde/core/patient-clinical-data";
import { z } from "zod";

export function createDeleteDocument(overrides: Partial<DeleteDocument> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZDeleteDocumentSchema.parse(raw);
}
