/**
 * Update HL7MappingProfile DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/integration-interoperability.schemas";

/**
 * DTO: HL7MappingProfileUpdate
 * Direction: Request Body → Handler → Domain
 * Route: Update HL7 mapping profile
 * OpenAPI Source: schemas.HL7MappingProfileUpdate
 */
export const ZHL7MappingProfileUpdateSchema = schemas.HL7MappingProfileUpdate;
export type HL7MappingProfileUpdate = z.infer<typeof ZHL7MappingProfileUpdateSchema>;
