/**
 * Create ModelInvocation DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/decision-intelligence.schemas";

/**
 * DTO: ModelInvocationInput
 * Direction: Request Body → Handler → Domain
 * Route: Create model invocation (immutable)
 * OpenAPI Source: schemas.ModelInvocationInput
 */
export const ZModelInvocationInputSchema = schemas.ModelInvocationInput;
export type ModelInvocationInput = z.infer<typeof ZModelInvocationInputSchema>;
