/**
 * Create Allergy DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/patient-clinical-data.schemas";

/**
 * DTO: AllergyInput
 * Direction: Request Body → Handler → Domain
 * Route: Create allergy
 * OpenAPI Source: schemas.AllergyInput
 */
export const ZAllergyInputSchema = schemas.AllergyInput;
export type AllergyInput = z.infer<typeof ZAllergyInputSchema>;
