/**
 * Update Allergy DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/patient-clinical-data.schemas";

/**
 * DTO: AllergyUpdate
 * Direction: Request Body → Handler → Domain
 * Route: Update allergy
 * OpenAPI Source: schemas.AllergyUpdate
 */
export const ZAllergyUpdateSchema = schemas.AllergyUpdate;
export type AllergyUpdate = z.infer<typeof ZAllergyUpdateSchema>;
