/**
 * Create DecisionSession DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/decision-intelligence.schemas";

/**
 * DTO: DecisionSessionInput
 * Direction: Request Body → Handler → Domain
 * Route: Create decision session
 * OpenAPI Source: schemas.DecisionSessionInput
 */
export const ZDecisionSessionInputSchema = schemas.DecisionSessionInput;
export type DecisionSessionInput = z.infer<typeof ZDecisionSessionInputSchema>;
