/**
 * Update DecisionSession DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/decision-intelligence.schemas";

/**
 * DTO: DecisionSessionUpdate
 * Direction: Request Body → Handler → Domain
 * Route: Update decision session
 * OpenAPI Source: schemas.DecisionSessionUpdate
 */
export const ZDecisionSessionUpdateSchema = schemas.DecisionSessionUpdate;
export type DecisionSessionUpdate = z.infer<typeof ZDecisionSessionUpdateSchema>;
