/**
 * WorkflowCarePathways Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { EpisodeOfCareUpdate } from "@cuur/core/workflow-care-pathways/models/episode-of-care/index.js";
import { workflowcarepathwaysSchemas as schemas } from "@cuur/core/workflow-care-pathways/index.js";
import { z } from "zod";

export function createEpisodeOfCareUpdate(overrides: Partial<EpisodeOfCareUpdate> = {}) {
  const raw = {
    condition: overrides.condition ?? faker.string.alpha(10),
    endDate: overrides.endDate ?? new Date().toISOString(),
    metadata: overrides.metadata ?? {},
    status: overrides.status ?? faker.helpers.arrayElement(["active", "completed", "cancelled"]),
    ...overrides,
  };

  return schemas.EpisodeOfCareUpdate.parse(raw);
}
