/**
 * Repository interface for DecisionSessionAlert
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../../_shared/src/repositories/_base-repository.js";

import type {
  DecisionSessionAlert
} from "../types/index.js";
/**
 * DecisionSessionAlertRepository Interface
 */
export interface DecisionSessionAlertRepository extends ReadRepository<DecisionSessionAlert, string, Record<string, never>> {

}
