/**
 * Repository interface for DecisionPolicyThresholdProfile
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "@cuur-cde/core/_shared";

import type {
  DecisionPolicyThresholdProfile
} from "@cuur-cde/core/decision-intelligence/types";
/**
 * DecisionPolicyThresholdProfileRepository Interface
 */
export interface DecisionPolicyThresholdProfileRepository extends ReadRepository<DecisionPolicyThresholdProfile, string, Record<string, never>> {

}
