/**
 * Repository interface for RiskAssessment
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "../../../_shared/src/repositories/_base-repository.js";

import type {
  RiskAssessment,
  ListRiskAssessmentsParams,
  UpdateRiskAssessmentRequest
} from "../types/index.js";
/**
 * RiskAssessmentRepository Interface
 */
export interface RiskAssessmentRepository extends CrudRepository<RiskAssessment, RiskAssessment, UpdateRiskAssessmentRequest, string, ListRiskAssessmentsParams> {

}
