/**
 * Repository interface for ThresholdProfile
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "@cuur-cde/core/_shared";

import type {
  ThresholdProfile,
  ListThresholdProfilesParams,
  UpdateThresholdProfileRequest
} from "@cuur-cde/core/decision-intelligence/types";
/**
 * ThresholdProfileRepository Interface
 */
export interface ThresholdProfileRepository extends CrudRepository<ThresholdProfile, ThresholdProfile, UpdateThresholdProfileRequest, string, ListThresholdProfilesParams> {

}
