/**
 * Get RoutingRule DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetRoutingRulePath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get routing rule by ID
 */
export const ZGetRoutingRulePathSchema = z.object({
  routingRuleId: z.string(),
});

export type GetRoutingRulePath = z.infer<typeof ZGetRoutingRulePathSchema>;
