/**
 * PatientLab schemas
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

// Auto-generated barrel export
export * from "./entity/patient-lab.entity";
export * from "./dto/list-patient-lab.dto";
