/**
 * IntegrationInteroperability Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListIntegrationJobParams, ZListIntegrationJobParamsSchema } from "@cuur-cde/core/integration-interoperability/models/integration-job/index.js";
import { z } from "zod";

export function createListIntegrationJobParams(overrides: Partial<ListIntegrationJobParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListIntegrationJobParamsSchema.parse(raw);
}
