/**
 * ExternalSystemEndpoint Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodTypeAny } from "zod";
import { schemas } from "../../../schemas/integration-interoperability.schemas.js";

/**
 * Entity: ExternalSystemEndpointEntity
 * Description: Represents the ExternalSystemEndpoint domain model.
 * Source: schemas.ExternalSystemEndpoint
 */
export const ZExternalSystemEndpointEntitySchema = schemas.ExternalSystemEndpoint as ZodTypeAny;
export type ExternalSystemEndpointEntity = z.infer<typeof ZExternalSystemEndpointEntitySchema>;
