/**
 * Routes for diagnosticReportImagingStudies
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import { extractOrgId } from "../extract-org-id.js";
import type { Dependencies } from "../dependencies/patient-clinical-data.dependencies.js";
import { listDiagnosticReportImagingStudies } from "@cuur-cde/core/patient-clinical-data/handlers/index.js";
export async function diagnosticReportImagingStudiesRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /diagnostic-reports/{id}/imaging-studies
  fastify.get("/diagnostic-reports/:id/imaging-studies", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listDiagnosticReportImagingStudies(deps.diagnosticReportImagingStudyRepo, orgId);
    return reply.code(200).send(result);
  });

}
