/**
 * Routes for diagnosticReportObservations
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import { extractOrgId } from "../context/org-context.js";
import type { Dependencies } from "../dependencies/patient-clinical-data.dependencies.js";
import { listDiagnosticReportObservations } from "@cuur-cde/core/patient-clinical-data/handlers/index.js";
export async function diagnosticReportObservationsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /diagnostic-reports/{id}/observations (nested route)
  fastify.get("/diagnostic-reports/:id/observations", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listDiagnosticReportObservations(deps.diagnosticReportObservationRepo, orgId);
    return reply.code(200).send(result);
  });

  // GET /diagnostic-report-observations (flat route for dashboard)
  fastify.get("/diagnostic-report-observations", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listDiagnosticReportObservations(deps.diagnosticReportObservationRepo, orgId);
    return reply.code(200).send(result);
  });

}
