/**
 * Routes for patientImmunizations
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/patient-clinical-data.dependencies.js";
import { listPatientImmunizations } from "@cuur-cde/core/patient-clinical-data/handlers/index.js";
export async function patientImmunizationsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /patients/{id}/immunizations
  fastify.get("/patients/:id/immunizations", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listPatientImmunizations(deps.patientImmunizationRepo, orgId);
    return reply.code(200).send(result);
  });

}
