/**
 * Routes for patientAllergies
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/patient-clinical-data.dependencies.js";
import { listPatientAllergies } from "@cuur-cde/core/patient-clinical-data/handlers/index.js";
export async function patientAllergiesRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /patients/{id}/allergies
  fastify.get("/patients/:id/allergies", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listPatientAllergies(deps.patientAllergyRepo, orgId);
    return reply.code(200).send(result);
  });

}
