export interface ServiceResource {
  id: string;
  name: string;
  description: string;
  path: string;
}

export interface Service {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  resources: ServiceResource[];
  category: "core" | "data" | "integration" | "workflow";
}

export const services: Service[] = [
  {
    id: "decision-intelligence",
    name: "Decision Intelligence",
    description: "AI-powered decision support, risk assessments, and clinical recommendations",
    icon: "🧠",
    color: "#f48fb1",
    category: "core",
    resources: [
      {
        id: "decision-sessions",
        name: "Decision Sessions",
        description: "Manage decision sessions",
        path: "/decision-sessions",
      },
      {
        id: "decision-session-requests",
        name: "Decision Session Requests",
        description: "Decision session request management",
        path: "/decision-session-requests",
      },
      {
        id: "decision-session-results",
        name: "Decision Session Results",
        description: "Results from decision sessions",
        path: "/decision-session-results",
      },
      {
        id: "decision-session-risk-assessments",
        name: "Decision Session Risk Assessments",
        description: "Risk assessments within decision sessions",
        path: "/decision-session-risk-assessments",
      },
      {
        id: "decision-session-alerts",
        name: "Decision Session Alerts",
        description: "Alerts generated in decision sessions",
        path: "/decision-session-alerts",
      },
      {
        id: "decision-session-explanations",
        name: "Decision Session Explanations",
        description: "Explanations for decision session outcomes",
        path: "/decision-session-explanations",
      },
      {
        id: "decision-requests",
        name: "Decision Requests",
        description: "Individual decision requests",
        path: "/decision-requests",
      },
      {
        id: "decision-request-results",
        name: "Decision Request Results",
        description: "Results from decision requests",
        path: "/decision-request-results",
      },
      {
        id: "decision-request-explanations",
        name: "Decision Request Explanations",
        description: "Explanations for decision request outcomes",
        path: "/decision-request-explanations",
      },
      {
        id: "decision-results",
        name: "Decision Results",
        description: "Decision result records",
        path: "/decision-results",
      },
      {
        id: "decision-result-recommendations",
        name: "Decision Result Recommendations",
        description: "Recommendations from decision results",
        path: "/decision-result-recommendations",
      },
      {
        id: "decision-result-risk-assessments",
        name: "Decision Result Risk Assessments",
        description: "Risk assessments from decision results",
        path: "/decision-result-risk-assessments",
      },
      {
        id: "decision-result-explanations",
        name: "Decision Result Explanations",
        description: "Explanations for decision results",
        path: "/decision-result-explanations",
      },
      {
        id: "risk-assessments",
        name: "Risk Assessments",
        description: "Patient risk evaluation",
        path: "/risk-assessments",
      },
      {
        id: "risk-assessment-explanations",
        name: "Risk Assessment Explanations",
        description: "Explanations for risk assessments",
        path: "/risk-assessment-explanations",
      },
      {
        id: "recommendations",
        name: "Recommendations",
        description: "Clinical recommendations",
        path: "/recommendations",
      },
      {
        id: "recommendation-explanations",
        name: "Recommendation Explanations",
        description: "Explanations for recommendations",
        path: "/recommendation-explanations",
      },
      {
        id: "alert-evaluations",
        name: "Alert Evaluations",
        description: "Alert assessment and management",
        path: "/alert-evaluations",
      },
      {
        id: "explanations",
        name: "Explanations",
        description: "General explanation records",
        path: "/explanations",
      },
      {
        id: "explanation-features",
        name: "Explanation Features",
        description: "Features used in explanations",
        path: "/explanation-features",
      },
      {
        id: "explanation-rule-traces",
        name: "Explanation Rule Traces",
        description: "Rule execution traces in explanations",
        path: "/explanation-rule-traces",
      },
      {
        id: "model-invocations",
        name: "Model Invocations",
        description: "ML model execution tracking",
        path: "/model-invocations",
      },
      {
        id: "model-invocation-explanations",
        name: "Model Invocation Explanations",
        description: "Explanations for model invocations",
        path: "/model-invocation-explanations",
      },
      {
        id: "simulation-scenarios",
        name: "Simulation Scenarios",
        description: "Clinical simulation scenario definitions",
        path: "/simulation-scenarios",
      },
      {
        id: "simulation-scenario-runs",
        name: "Simulation Scenario Runs",
        description: "Runs of simulation scenarios",
        path: "/simulation-scenario-runs",
      },
      {
        id: "simulation-runs",
        name: "Simulation Runs",
        description: "Clinical scenario simulations",
        path: "/simulation-runs",
      },
      {
        id: "simulation-run-decision-results",
        name: "Simulation Run Decision Results",
        description: "Decision results from simulation runs",
        path: "/simulation-run-decision-results",
      },
      {
        id: "simulation-run-metrics",
        name: "Simulation Run Metrics",
        description: "Performance metrics from simulation runs",
        path: "/simulation-run-metrics",
      },
      {
        id: "decision-policies",
        name: "Decision Policies",
        description: "Policy configuration",
        path: "/decision-policies",
      },
      {
        id: "decision-policy-threshold-profiles",
        name: "Decision Policy Threshold Profiles",
        description: "Threshold profiles for decision policies",
        path: "/decision-policy-threshold-profiles",
      },
      {
        id: "threshold-profiles",
        name: "Threshold Profiles",
        description: "Threshold profile definitions",
        path: "/threshold-profiles",
      },
      {
        id: "decision-metrics",
        name: "Decision Metrics",
        description: "Performance analytics",
        path: "/decision-metrics",
      },
      {
        id: "decision-metric-snapshots",
        name: "Decision Metric Snapshots",
        description: "Time-series snapshots of decision metrics",
        path: "/decision-metric-snapshots",
      },
      {
        id: "experiments",
        name: "Experiments",
        description: "A/B testing and experiments",
        path: "/experiments",
      },
      {
        id: "experiment-arms",
        name: "Experiment Arms",
        description: "Experimental arms/conditions",
        path: "/experiment-arms",
      },
      {
        id: "experiment-results",
        name: "Experiment Results",
        description: "Results from experiments",
        path: "/experiment-results",
      },
    ],
  },
  {
    id: "knowledge-evidence",
    name: "Knowledge & Evidence",
    description: "Clinical rules, guidelines, ontologies, and evidence-based knowledge",
    icon: "📚",
    color: "#81c995",
    category: "core",
    resources: [
      {
        id: "clinical-rules",
        name: "Clinical Rules",
        description: "Rule-based decision logic",
        path: "/clinical-rules",
      },
      {
        id: "clinical-rule-versions",
        name: "Clinical Rule Versions",
        description: "Version history of clinical rules",
        path: "/clinical-rule-versions",
      },
      {
        id: "clinical-rule-tests",
        name: "Clinical Rule Tests",
        description: "Test cases for clinical rules",
        path: "/clinical-rule-tests",
      },
      {
        id: "rule-sets",
        name: "Rule Sets",
        description: "Collections of clinical rules",
        path: "/rule-sets",
      },
      {
        id: "rule-set-clinical-rules",
        name: "Rule Set Clinical Rules",
        description: "Clinical rules within rule sets",
        path: "/rule-set-clinical-rules",
      },
      {
        id: "guidelines",
        name: "Guidelines",
        description: "Clinical practice guidelines",
        path: "/guidelines",
      },
      {
        id: "guideline-sections",
        name: "Guideline Sections",
        description: "Sections within guidelines",
        path: "/guideline-sections",
      },
      {
        id: "guideline-evidence-citations",
        name: "Guideline Evidence Citations",
        description: "Evidence citations in guidelines",
        path: "/guideline-evidence-citations",
      },
      {
        id: "care-protocols",
        name: "Care Protocols",
        description: "Standardized care pathways",
        path: "/care-protocols",
      },
      {
        id: "care-protocol-steps",
        name: "Care Protocol Steps",
        description: "Steps within care protocols",
        path: "/care-protocol-steps",
      },
      {
        id: "care-protocol-order-sets",
        name: "Care Protocol Order Sets",
        description: "Order sets within care protocols",
        path: "/care-protocol-order-sets",
      },
      {
        id: "order-set-templates",
        name: "Order Set Templates",
        description: "Templates for order sets",
        path: "/order-set-templates",
      },
      {
        id: "order-set-template-items",
        name: "Order Set Template Items",
        description: "Items within order set templates",
        path: "/order-set-template-items",
      },
      {
        id: "model-definitions",
        name: "Model Definitions",
        description: "ML model configurations",
        path: "/model-definitions",
      },
      {
        id: "model-definition-versions",
        name: "Model Definition Versions",
        description: "Version history of model definitions",
        path: "/model-definition-versions",
      },
      {
        id: "model-definition-performance-metrics",
        name: "Model Definition Performance Metrics",
        description: "Performance metrics for model definitions",
        path: "/model-definition-performance-metrics",
      },
      {
        id: "model-versions",
        name: "Model Versions",
        description: "Versioned ML models",
        path: "/model-versions",
      },
      {
        id: "model-version-tests",
        name: "Model Version Tests",
        description: "Test cases for model versions",
        path: "/model-version-tests",
      },
      {
        id: "model-version-feature-definitions",
        name: "Model Version Feature Definitions",
        description: "Feature definitions for model versions",
        path: "/model-version-feature-definitions",
      },
      {
        id: "ontology-terms",
        name: "Ontology Terms",
        description: "Medical terminology",
        path: "/ontology-terms",
      },
      {
        id: "ontology-term-children",
        name: "Ontology Term Children",
        description: "Child terms in ontology hierarchy",
        path: "/ontology-term-children",
      },
      {
        id: "ontology-term-parents",
        name: "Ontology Term Parents",
        description: "Parent terms in ontology hierarchy",
        path: "/ontology-term-parents",
      },
      {
        id: "ontology-term-mappings",
        name: "Ontology Term Mappings",
        description: "Mappings between ontology terms",
        path: "/ontology-term-mappings",
      },
      {
        id: "value-sets",
        name: "Value Sets",
        description: "Coded value collections",
        path: "/value-sets",
      },
      {
        id: "value-set-codes",
        name: "Value Set Codes",
        description: "Codes within value sets",
        path: "/value-set-codes",
      },
      {
        id: "concept-maps",
        name: "Concept Maps",
        description: "Terminology mappings",
        path: "/concept-maps",
      },
      {
        id: "concept-map-mappings",
        name: "Concept Map Mappings",
        description: "Individual mappings within concept maps",
        path: "/concept-map-mappings",
      },
      {
        id: "scoring-templates",
        name: "Scoring Templates",
        description: "Templates for scoring systems",
        path: "/scoring-templates",
      },
      {
        id: "scoring-template-items",
        name: "Scoring Template Items",
        description: "Items within scoring templates",
        path: "/scoring-template-items",
      },
      {
        id: "questionnaire-templates",
        name: "Questionnaire Templates",
        description: "Templates for questionnaires",
        path: "/questionnaire-templates",
      },
      {
        id: "questionnaire-template-questions",
        name: "Questionnaire Template Questions",
        description: "Questions within questionnaire templates",
        path: "/questionnaire-template-questions",
      },
      {
        id: "evidence-citations",
        name: "Evidence Citations",
        description: "Citations of clinical evidence",
        path: "/evidence-citations",
      },
      {
        id: "evidence-reviews",
        name: "Evidence Reviews",
        description: "Systematic evidence reviews",
        path: "/evidence-reviews",
      },
      {
        id: "knowledge-packages",
        name: "Knowledge Packages",
        description: "Bundled knowledge artifacts",
        path: "/knowledge-packages",
      },
      {
        id: "knowledge-package-clinical-rules",
        name: "Knowledge Package Clinical Rules",
        description: "Clinical rules in knowledge packages",
        path: "/knowledge-package-clinical-rules",
      },
      {
        id: "knowledge-package-model-definitions",
        name: "Knowledge Package Model Definitions",
        description: "Model definitions in knowledge packages",
        path: "/knowledge-package-model-definitions",
      },
      {
        id: "knowledge-package-value-sets",
        name: "Knowledge Package Value Sets",
        description: "Value sets in knowledge packages",
        path: "/knowledge-package-value-sets",
      },
    ],
  },
  {
    id: "patient-clinical-data",
    name: "Patient Clinical Data",
    description: "Patient records, encounters, observations, and clinical documentation",
    icon: "👤",
    color: "#64b5f6",
    category: "data",
    resources: [
      {
        id: "patients",
        name: "Patients",
        description: "Patient demographics and records",
        path: "/patients",
      },
      {
        id: "patient-summaries",
        name: "Patient Summaries",
        description: "Summary views of patient data",
        path: "/patient-summaries",
      },
      {
        id: "patient-encounters",
        name: "Patient Encounters",
        description: "Encounters for specific patients",
        path: "/patient-encounters",
      },
      {
        id: "patient-conditions",
        name: "Patient Conditions",
        description: "Conditions for specific patients",
        path: "/patient-conditions",
      },
      {
        id: "patient-allergies",
        name: "Patient Allergies",
        description: "Allergies for specific patients",
        path: "/patient-allergies",
      },
      {
        id: "patient-medications",
        name: "Patient Medications",
        description: "Medications for specific patients",
        path: "/patient-medications",
      },
      {
        id: "patient-immunizations",
        name: "Patient Immunizations",
        description: "Immunizations for specific patients",
        path: "/patient-immunizations",
      },
      {
        id: "patient-observations",
        name: "Patient Observations",
        description: "Observations for specific patients",
        path: "/patient-observations",
      },
      {
        id: "patient-vitals",
        name: "Patient Vitals",
        description: "Vital signs for specific patients",
        path: "/patient-vitals",
      },
      {
        id: "patient-labs",
        name: "Patient Labs",
        description: "Lab results for specific patients",
        path: "/patient-labs",
      },
      {
        id: "patient-diagnostic-reports",
        name: "Patient Diagnostic Reports",
        description: "Diagnostic reports for specific patients",
        path: "/patient-diagnostic-reports",
      },
      {
        id: "patient-procedures",
        name: "Patient Procedures",
        description: "Procedures for specific patients",
        path: "/patient-procedures",
      },
      {
        id: "patient-notes",
        name: "Patient Notes",
        description: "Clinical notes for specific patients",
        path: "/patient-notes",
      },
      {
        id: "patient-care-teams",
        name: "Patient Care Teams",
        description: "Care teams for specific patients",
        path: "/patient-care-teams",
      },
      {
        id: "patient-documents",
        name: "Patient Documents",
        description: "Documents for specific patients",
        path: "/patient-documents",
      },
      {
        id: "encounters",
        name: "Encounters",
        description: "Clinical encounters",
        path: "/encounters",
      },
      {
        id: "encounter-conditions",
        name: "Encounter Conditions",
        description: "Conditions within encounters",
        path: "/encounter-conditions",
      },
      {
        id: "encounter-observations",
        name: "Encounter Observations",
        description: "Observations within encounters",
        path: "/encounter-observations",
      },
      {
        id: "encounter-diagnostic-reports",
        name: "Encounter Diagnostic Reports",
        description: "Diagnostic reports within encounters",
        path: "/encounter-diagnostic-reports",
      },
      {
        id: "encounter-procedures",
        name: "Encounter Procedures",
        description: "Procedures within encounters",
        path: "/encounter-procedures",
      },
      {
        id: "encounter-notes",
        name: "Encounter Notes",
        description: "Notes within encounters",
        path: "/encounter-notes",
      },
      {
        id: "conditions",
        name: "Conditions",
        description: "Patient conditions",
        path: "/conditions",
      },
      {
        id: "condition-notes",
        name: "Condition Notes",
        description: "Notes related to conditions",
        path: "/condition-notes",
      },
      {
        id: "allergies",
        name: "Allergies",
        description: "Patient allergies",
        path: "/allergies",
      },
      {
        id: "medication-statements",
        name: "Medication Statements",
        description: "Medication statement records",
        path: "/medication-statements",
      },
      {
        id: "medication-orders",
        name: "Medication Orders",
        description: "Medication order records",
        path: "/medication-orders",
      },
      {
        id: "medication-administrations",
        name: "Medication Administrations",
        description: "Medication administration records",
        path: "/medication-administrations",
      },
      {
        id: "immunizations",
        name: "Immunizations",
        description: "Vaccination records",
        path: "/immunizations",
      },
      {
        id: "observations",
        name: "Observations",
        description: "Clinical observations",
        path: "/observations",
      },
      {
        id: "diagnostic-reports",
        name: "Diagnostic Reports",
        description: "Lab and imaging reports",
        path: "/diagnostic-reports",
      },
      {
        id: "diagnostic-report-observations",
        name: "Diagnostic Report Observations",
        description: "Observations within diagnostic reports",
        path: "/diagnostic-report-observations",
      },
      {
        id: "diagnostic-report-imaging-studies",
        name: "Diagnostic Report Imaging Studies",
        description: "Imaging studies within diagnostic reports",
        path: "/diagnostic-report-imaging-studies",
      },
      {
        id: "imaging-studies",
        name: "Imaging Studies",
        description: "Medical imaging study records",
        path: "/imaging-studies",
      },
      {
        id: "imaging-study-series",
        name: "Imaging Study Series",
        description: "Series within imaging studies",
        path: "/imaging-study-series",
      },
      {
        id: "procedures",
        name: "Procedures",
        description: "Clinical procedures",
        path: "/procedures",
      },
      {
        id: "notes",
        name: "Notes",
        description: "Clinical notes",
        path: "/notes",
      },
      {
        id: "care-teams",
        name: "Care Teams",
        description: "Care team records",
        path: "/care-teams",
      },
      {
        id: "documents",
        name: "Documents",
        description: "Clinical documents",
        path: "/documents",
      },
    ],
  },
  {
    id: "workflow-care-pathways",
    name: "Workflow & Care Pathways",
    description: "Care plans, workflows, tasks, and care pathway management",
    icon: "🔄",
    color: "#4dd0e1",
    category: "workflow",
    resources: [
      {
        id: "workflow-definitions",
        name: "Workflow Definitions",
        description: "Workflow definition templates",
        path: "/workflow-definitions",
      },
      {
        id: "workflow-definition-states",
        name: "Workflow Definition States",
        description: "States within workflow definitions",
        path: "/workflow-definition-states",
      },
      {
        id: "workflow-definition-transitions",
        name: "Workflow Definition Transitions",
        description: "Transitions between workflow states",
        path: "/workflow-definition-transitions",
      },
      {
        id: "workflow-instances",
        name: "Workflow Instances",
        description: "Active workflow executions",
        path: "/workflow-instances",
      },
      {
        id: "workflow-instance-tasks",
        name: "Workflow Instance Tasks",
        description: "Tasks within workflow instances",
        path: "/workflow-instance-tasks",
      },
      {
        id: "workflow-instance-events",
        name: "Workflow Instance Events",
        description: "Events within workflow instances",
        path: "/workflow-instance-events",
      },
      {
        id: "workflow-instance-audit-events",
        name: "Workflow Instance Audit Events",
        description: "Audit trail for workflow instances",
        path: "/workflow-instance-audit-events",
      },
      {
        id: "care-pathway-templates",
        name: "Care Pathway Templates",
        description: "Template definitions",
        path: "/care-pathway-templates",
      },
      {
        id: "care-pathway-template-steps",
        name: "Care Pathway Template Steps",
        description: "Steps within care pathway templates",
        path: "/care-pathway-template-steps",
      },
      {
        id: "care-pathway-template-order-set-templates",
        name: "Care Pathway Template Order Set Templates",
        description: "Order set templates in care pathway templates",
        path: "/care-pathway-template-order-set-templates",
      },
      {
        id: "care-plans",
        name: "Care Plans",
        description: "Patient care plans",
        path: "/care-plans",
      },
      {
        id: "care-plan-goals",
        name: "Care Plan Goals",
        description: "Goals within care plans",
        path: "/care-plan-goals",
      },
      {
        id: "care-plan-tasks",
        name: "Care Plan Tasks",
        description: "Tasks within care plans",
        path: "/care-plan-tasks",
      },
      {
        id: "care-plan-checklists",
        name: "Care Plan Checklists",
        description: "Checklists within care plans",
        path: "/care-plan-checklists",
      },
      {
        id: "episodes-of-cares",
        name: "Episodes of Cares",
        description: "Multiple episodes of care",
        path: "/episodes-of-cares",
      },
      {
        id: "episode-of-cares",
        name: "Episode of Cares",
        description: "Individual episode of care records",
        path: "/episode-of-cares",
      },
      {
        id: "episode-of-care-encounters",
        name: "Episode of Care Encounters",
        description: "Encounters within episodes of care",
        path: "/episode-of-care-encounters",
      },
      {
        id: "episode-of-care-care-plans",
        name: "Episode of Care Care Plans",
        description: "Care plans within episodes of care",
        path: "/episode-of-care-care-plans",
      },
      {
        id: "episode-of-care-workflow-instances",
        name: "Episode of Care Workflow Instances",
        description: "Workflow instances within episodes of care",
        path: "/episode-of-care-workflow-instances",
      },
      {
        id: "tasks",
        name: "Tasks",
        description: "Clinical tasks and assignments",
        path: "/tasks",
      },
      {
        id: "task-comments",
        name: "Task Comments",
        description: "Comments on tasks",
        path: "/task-comments",
      },
      {
        id: "task-audit-events",
        name: "Task Audit Events",
        description: "Audit trail for tasks",
        path: "/task-audit-events",
      },
      {
        id: "task-assignments",
        name: "Task Assignments",
        description: "Assignments of tasks to users",
        path: "/task-assignments",
      },
      {
        id: "alerts",
        name: "Alerts",
        description: "Clinical alerts and notifications",
        path: "/alerts",
      },
      {
        id: "alert-explanations",
        name: "Alert Explanations",
        description: "Explanations for alerts",
        path: "/alert-explanations",
      },
      {
        id: "alert-audit-events",
        name: "Alert Audit Events",
        description: "Audit trail for alerts",
        path: "/alert-audit-events",
      },
      {
        id: "handoffs",
        name: "Handoffs",
        description: "Care handoff records",
        path: "/handoffs",
      },
      {
        id: "handoff-tasks",
        name: "Handoff Tasks",
        description: "Tasks within handoffs",
        path: "/handoff-tasks",
      },
      {
        id: "checklist-templates",
        name: "Checklist Templates",
        description: "Templates for checklists",
        path: "/checklist-templates",
      },
      {
        id: "checklist-template-items",
        name: "Checklist Template Items",
        description: "Items within checklist templates",
        path: "/checklist-template-items",
      },
      {
        id: "checklist-instances",
        name: "Checklist Instances",
        description: "Clinical checklists",
        path: "/checklist-instances",
      },
      {
        id: "checklist-instance-items",
        name: "Checklist Instance Items",
        description: "Items within checklist instances",
        path: "/checklist-instance-items",
      },
      {
        id: "escalation-policies",
        name: "Escalation Policies",
        description: "Escalation policy definitions",
        path: "/escalation-policies",
      },
      {
        id: "escalation-policy-rules",
        name: "Escalation Policy Rules",
        description: "Rules within escalation policies",
        path: "/escalation-policy-rules",
      },
      {
        id: "routing-rules",
        name: "Routing Rules",
        description: "Rules for routing tasks and alerts",
        path: "/routing-rules",
      },
      {
        id: "schedule-templates",
        name: "Schedule Templates",
        description: "Templates for scheduling",
        path: "/schedule-templates",
      },
      {
        id: "work-queues",
        name: "Work Queues",
        description: "Task queues and assignments",
        path: "/work-queues",
      },
      {
        id: "work-queue-tasks",
        name: "Work Queue Tasks",
        description: "Tasks within work queues",
        path: "/work-queue-tasks",
      },
      {
        id: "work-queue-alerts",
        name: "Work Queue Alerts",
        description: "Alerts within work queues",
        path: "/work-queue-alerts",
      },
    ],
  },
  {
    id: "integration-interoperability",
    name: "Integration & Interoperability",
    description: "External system integrations, FHIR/HL7 mappings, and data exchange",
    icon: "🔌",
    color: "#ffb74d",
    category: "integration",
    resources: [
      {
        id: "external-systems",
        name: "External Systems",
        description: "Connected external systems",
        path: "/external-systems",
      },
      {
        id: "external-system-endpoints",
        name: "External System Endpoints",
        description: "Endpoints for external systems",
        path: "/external-system-endpoints",
      },
      {
        id: "external-system-connections",
        name: "External System Connections",
        description: "Connections to external systems",
        path: "/external-system-connections",
      },
      {
        id: "external-system-integration-jobs",
        name: "External System Integration Jobs",
        description: "Integration jobs for external systems",
        path: "/external-system-integration-jobs",
      },
      {
        id: "connections",
        name: "Connections",
        description: "System connections",
        path: "/connections",
      },
      {
        id: "connection-health-checks",
        name: "Connection Health Checks",
        description: "Health check results for connections",
        path: "/connection-health-checks",
      },
      {
        id: "connection-integration-jobs",
        name: "Connection Integration Jobs",
        description: "Integration jobs for connections",
        path: "/connection-integration-jobs",
      },
      {
        id: "fhir-bundles",
        name: "FHIR Bundles",
        description: "FHIR resource bundles",
        path: "/f-hirbundles",
      },
      {
        id: "fhir-bundle-resources",
        name: "FHIR Bundle Resources",
        description: "Resources within FHIR bundles",
        path: "/f-hirbundle-resources",
      },
      {
        id: "fhir-mapping-profiles",
        name: "FHIR Mapping Profiles",
        description: "Mapping profiles for FHIR resources",
        path: "/fhir-mapping-profiles",
      },
      {
        id: "fhir-mapping-profile-rules",
        name: "FHIR Mapping Profile Rules",
        description: "Rules within FHIR mapping profiles",
        path: "/f-hirmapping-profile-rules",
      },
      {
        id: "hl7-messages",
        name: "HL7 Messages",
        description: "HL7 message processing",
        path: "/hl7-messages",
      },
      {
        id: "hl7-message-segments",
        name: "HL7 Message Segments",
        description: "Segments within HL7 messages",
        path: "/h-lmessage-segments",
      },
      {
        id: "hl7-message-mapping-results",
        name: "HL7 Message Mapping Results",
        description: "Mapping results for HL7 messages",
        path: "/h-lmessage-mapping-results",
      },
      {
        id: "hl7-mapping-profiles",
        name: "HL7 Mapping Profiles",
        description: "Mapping profiles for HL7 messages",
        path: "/hl7-mapping-profiles",
      },
      {
        id: "hl7-mapping-profile-rules",
        name: "HL7 Mapping Profile Rules",
        description: "Rules within HL7 mapping profiles",
        path: "/h-lmapping-profile-rules",
      },
      {
        id: "integration-jobs",
        name: "Integration Jobs",
        description: "Scheduled integrations",
        path: "/integration-jobs",
      },
      {
        id: "integration-job-runs",
        name: "Integration Job Runs",
        description: "Execution runs of integration jobs",
        path: "/integration-job-runs",
      },
      {
        id: "integration-runs",
        name: "Integration Runs",
        description: "Integration execution history",
        path: "/integration-runs",
      },
      {
        id: "integration-run-logs",
        name: "Integration Run Logs",
        description: "Logs from integration runs",
        path: "/integration-run-logs",
      },
      {
        id: "integration-run-errors",
        name: "Integration Run Errors",
        description: "Errors from integration runs",
        path: "/integration-run-errors",
      },
      {
        id: "data-import-batches",
        name: "Data Import Batches",
        description: "Bulk data imports",
        path: "/data-import-batches",
      },
      {
        id: "data-import-batch-records",
        name: "Data Import Batch Records",
        description: "Records within import batches",
        path: "/data-import-batch-records",
      },
      {
        id: "data-import-batch-errors",
        name: "Data Import Batch Errors",
        description: "Errors in import batches",
        path: "/data-import-batch-errors",
      },
      {
        id: "data-export-batches",
        name: "Data Export Batches",
        description: "Bulk data exports",
        path: "/data-export-batches",
      },
      {
        id: "data-export-batch-files",
        name: "Data Export Batch Files",
        description: "Files from export batches",
        path: "/data-export-batch-files",
      },
      {
        id: "data-export-batch-errors",
        name: "Data Export Batch Errors",
        description: "Errors in export batches",
        path: "/data-export-batch-errors",
      },
      {
        id: "event-subscriptions",
        name: "Event Subscriptions",
        description: "Subscriptions to system events",
        path: "/event-subscriptions",
      },
      {
        id: "event-subscription-deliveries",
        name: "Event Subscription Deliveries",
        description: "Deliveries for event subscriptions",
        path: "/event-subscription-deliveries",
      },
      {
        id: "event-deliveries",
        name: "Event Deliveries",
        description: "Event delivery records",
        path: "/event-deliveries",
      },
      {
        id: "api-clients",
        name: "API Clients",
        description: "API client management",
        path: "/a-piclients",
      },
      {
        id: "api-client-credentials",
        name: "API Client Credentials",
        description: "Credentials for API clients",
        path: "/a-piclient-credentials",
      },
      {
        id: "api-client-usage-metrics",
        name: "API Client Usage Metrics",
        description: "Usage metrics for API clients",
        path: "/a-piclient-usage-metrics",
      },
      {
        id: "api-credentials",
        name: "API Credentials",
        description: "General API credentials",
        path: "/a-picredentials",
      },
      {
        id: "interface-errors",
        name: "Interface Errors",
        description: "Errors from system interfaces",
        path: "/interface-errors",
      },
      {
        id: "interface-health-checks",
        name: "Interface Health Checks",
        description: "Health check results for interfaces",
        path: "/interface-health-checks",
      },
    ],
  },
];

export const getServiceById = (id: string): Service | undefined => {
  return services.find((s) => s.id === id);
};

export const getResourceById = (
  serviceId: string,
  resourceId: string
): ServiceResource | undefined => {
  const service = getServiceById(serviceId);
  return service?.resources.find((r) => r.id === resourceId);
};

/**
 * Get API path for a resource
 */
export const getResourceApiPath = (serviceId: string, resourceId: string): string | undefined => {
  const resource = getResourceById(serviceId, resourceId);
  return resource?.path;
};
