/**
 * KnowledgeEvidence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ModelVersionInput } from "@cuur-cde/core/knowledge-evidence/models/model-version/index.js";
import { knowledgeevidenceSchemas as schemas } from "@cuur-cde/core/knowledge-evidence/index.js";
import { z } from "zod";

export function createModelVersionInput(overrides: Partial<ModelVersionInput> = {}) {
  const raw = {
    artifactUrl: overrides.artifactUrl ?? faker.internet.url(),
    metadata: overrides.metadata ?? {},
    modelDefinitionId: overrides.modelDefinitionId ?? faker.string.alpha(10),
    performanceMetrics: overrides.performanceMetrics ?? {},
    status: overrides.status ?? faker.helpers.arrayElement(["training", "validated", "deployed", "deprecated"]),
    trainingDate: overrides.trainingDate ?? new Date().toISOString(),
    version: overrides.version ?? faker.string.alpha(10),
    ...overrides,
  };

  return schemas.ModelVersionInput.parse(raw);
}
