/**
 * List ImagingStudySeries DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListImagingStudySeriesParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /imaging-study-series
 */
export const ZListImagingStudySeriesParamsSchema = z.object({

});

export type ListImagingStudySeriesParams = z.infer<typeof ZListImagingStudySeriesParamsSchema>;
