/**
 * WorkflowCarePathways Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListWorkflowDefinitionTransitionParams, ZListWorkflowDefinitionTransitionParamsSchema } from "@cuur/core/workflow-care-pathways/models/workflow-definition-transition/index.js";
import { z } from "zod";

export function createListWorkflowDefinitionTransitionParams(overrides: Partial<ListWorkflowDefinitionTransitionParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListWorkflowDefinitionTransitionParamsSchema.parse(raw);
}
