/**
 * WorkflowCarePathways Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { DeleteCarePlan, ZDeleteCarePlanSchema } from "@cuur-cde/core/workflow-care-pathways/models/care-plan/index.js";
import { z } from "zod";

export function createDeleteCarePlan(overrides: Partial<DeleteCarePlan> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZDeleteCarePlanSchema.parse(raw);
}
