/**
 * PatientClinicalData Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { PatientInput } from "@cuur/core/patient-clinical-data/models/patient/index.js";
import { patientclinicaldataSchemas as schemas } from "@cuur/core/patient-clinical-data/index.js";
import { z } from "zod";

export function createPatientInput(overrides: Partial<PatientInput> = {}) {
  const raw = {
    address: overrides.address ?? [],
    birthDate: overrides.birthDate ?? faker.string.alpha(10),
    gender: overrides.gender ?? faker.helpers.arrayElement(["male", "female", "other", "unknown"]),
    identifiers: overrides.identifiers ?? [],
    patientId: overrides.patientId ?? faker.string.alpha(10),
    telecom: overrides.telecom ?? [],
    ...overrides,
  };

  return schemas.PatientInput.parse(raw);
}
