/**
 * PatientClinicalData Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { PatientUpdate } from "@cuur/core/patient-clinical-data/models/patient/index.js";
import { patientclinicaldataSchemas as schemas } from "@cuur/core/patient-clinical-data/index.js";
import { z } from "zod";

export function createPatientUpdate(overrides: Partial<PatientUpdate> = {}) {
  const raw = {
    address: overrides.address ?? [],
    gender: overrides.gender ?? faker.helpers.arrayElement(["male", "female", "other", "unknown"]),
    telecom: overrides.telecom ?? [],
    ...overrides,
  };

  return schemas.PatientUpdate.parse(raw);
}
