/**
 * DecisionIntelligence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { RecommendationInput } from "@cuur-cde/core/decision-intelligence";
import { decisionintelligenceSchemas as schemas } from "@cuur-cde/core/decision-intelligence/index.js";
import { z } from "zod";

export function createRecommendationInput(overrides: Partial<RecommendationInput> = {}) {
  const raw = {
    decisionResultId: overrides.decisionResultId ?? faker.string.alpha(10),
    description: overrides.description ?? faker.string.alpha(10),
    metadata: overrides.metadata ?? {},
    recommendationType: overrides.recommendationType ?? faker.helpers.arrayElement(["diagnostic", "treatment", "monitoring", "follow-up", "documentation", "other"]),
    status: overrides.status ?? faker.helpers.arrayElement(["pending", "accepted", "overridden", "deferred"]),
    suggestion: overrides.suggestion ?? {},
    title: overrides.title ?? faker.string.alpha(10),
    ...overrides,
  };

  return schemas.RecommendationInput.parse(raw);
}
