/**
 * Routes for episodeOfCareCarePlans
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/workflow-care-pathways.dependencies.js";
import { listEpisodeOfCareCarePlans } from "@cuur/core/workflow-care-pathways/handlers/index.js";
export async function episodeOfCareCarePlansRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /episodes-of-care/{id}/care-plans
  fastify.get("/episodes-of-care/:id/care-plans", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await listEpisodeOfCareCarePlans(deps.episodeOfCareCarePlanRepo, orgId);
    return reply.code(200).send(result);
  });

}
