/**
 * All route modules for the service
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/workflow-care-pathways.dependencies.js";

import { workflowDefinitionsRoutes } from "./workflow-definitions.routes.js";
import { workflowDefinitionStatesRoutes } from "./workflow-definition-states.routes.js";
import { workflowDefinitionTransitionsRoutes } from "./workflow-definition-transitions.routes.js";
import { workflowInstancesRoutes } from "./workflow-instances.routes.js";
import { workflowInstanceTasksRoutes } from "./workflow-instance-tasks.routes.js";
import { workflowInstanceEventsRoutes } from "./workflow-instance-events.routes.js";
import { workflowInstanceAuditEventsRoutes } from "./workflow-instance-audit-events.routes.js";
import { carePathwayTemplatesRoutes } from "./care-pathway-templates.routes.js";
import { carePathwayTemplateStepsRoutes } from "./care-pathway-template-steps.routes.js";
import { carePathwayTemplateOrderSetTemplatesRoutes } from "./care-pathway-template-order-set-templates.routes.js";
import { carePlansRoutes } from "./care-plans.routes.js";
import { carePlanGoalsRoutes } from "./care-plan-goals.routes.js";
import { carePlanTasksRoutes } from "./care-plan-tasks.routes.js";
import { carePlanChecklistsRoutes } from "./care-plan-checklists.routes.js";
import { episodesOfCaresRoutes } from "./episodes-of-cares.routes.js";
import { episodeOfCaresRoutes } from "./episode-of-cares.routes.js";
import { episodeOfCareEncountersRoutes } from "./episode-of-care-encounters.routes.js";
import { episodeOfCareCarePlansRoutes } from "./episode-of-care-care-plans.routes.js";
import { episodeOfCareWorkflowInstancesRoutes } from "./episode-of-care-workflow-instances.routes.js";
import { tasksRoutes } from "./tasks.routes.js";
import { taskCommentsRoutes } from "./task-comments.routes.js";
import { taskAuditEventsRoutes } from "./task-audit-events.routes.js";
import { taskAssignmentsRoutes } from "./task-assignments.routes.js";
import { alertsRoutes } from "./alerts.routes.js";
import { alertExplanationsRoutes } from "./alert-explanations.routes.js";
import { alertAuditEventsRoutes } from "./alert-audit-events.routes.js";
import { handoffsRoutes } from "./handoffs.routes.js";
import { handoffTasksRoutes } from "./handoff-tasks.routes.js";
import { checklistTemplatesRoutes } from "./checklist-templates.routes.js";
import { checklistTemplateItemsRoutes } from "./checklist-template-items.routes.js";
import { checklistInstancesRoutes } from "./checklist-instances.routes.js";
import { checklistInstanceItemsRoutes } from "./checklist-instance-items.routes.js";
import { escalationPoliciesRoutes } from "./escalation-policies.routes.js";
import { escalationPolicyRulesRoutes } from "./escalation-policy-rules.routes.js";
import { routingRulesRoutes } from "./routing-rules.routes.js";
import { scheduleTemplatesRoutes } from "./schedule-templates.routes.js";
import { workQueuesRoutes } from "./work-queues.routes.js";
import { workQueueTasksRoutes } from "./work-queue-tasks.routes.js";
import { workQueueAlertsRoutes } from "./work-queue-alerts.routes.js";

/**
 * Register all routes for workflow-care-pathways service
 */
export async function registerRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  await workflowDefinitionsRoutes(fastify, deps);
  await workflowDefinitionStatesRoutes(fastify, deps);
  await workflowDefinitionTransitionsRoutes(fastify, deps);
  await workflowInstancesRoutes(fastify, deps);
  await workflowInstanceTasksRoutes(fastify, deps);
  await workflowInstanceEventsRoutes(fastify, deps);
  await workflowInstanceAuditEventsRoutes(fastify, deps);
  await carePathwayTemplatesRoutes(fastify, deps);
  await carePathwayTemplateStepsRoutes(fastify, deps);
  await carePathwayTemplateOrderSetTemplatesRoutes(fastify, deps);
  await carePlansRoutes(fastify, deps);
  await carePlanGoalsRoutes(fastify, deps);
  await carePlanTasksRoutes(fastify, deps);
  await carePlanChecklistsRoutes(fastify, deps);
  await episodesOfCaresRoutes(fastify, deps);
  await episodeOfCaresRoutes(fastify, deps);
  await episodeOfCareEncountersRoutes(fastify, deps);
  await episodeOfCareCarePlansRoutes(fastify, deps);
  await episodeOfCareWorkflowInstancesRoutes(fastify, deps);
  await tasksRoutes(fastify, deps);
  await taskCommentsRoutes(fastify, deps);
  await taskAuditEventsRoutes(fastify, deps);
  await taskAssignmentsRoutes(fastify, deps);
  await alertsRoutes(fastify, deps);
  await alertExplanationsRoutes(fastify, deps);
  await alertAuditEventsRoutes(fastify, deps);
  await handoffsRoutes(fastify, deps);
  await handoffTasksRoutes(fastify, deps);
  await checklistTemplatesRoutes(fastify, deps);
  await checklistTemplateItemsRoutes(fastify, deps);
  await checklistInstancesRoutes(fastify, deps);
  await checklistInstanceItemsRoutes(fastify, deps);
  await escalationPoliciesRoutes(fastify, deps);
  await escalationPolicyRulesRoutes(fastify, deps);
  await routingRulesRoutes(fastify, deps);
  await scheduleTemplatesRoutes(fastify, deps);
  await workQueuesRoutes(fastify, deps);
  await workQueueTasksRoutes(fastify, deps);
  await workQueueAlertsRoutes(fastify, deps);
}

// Re-export individual route modules
export { workflowDefinitionsRoutes };
export { workflowDefinitionStatesRoutes };
export { workflowDefinitionTransitionsRoutes };
export { workflowInstancesRoutes };
export { workflowInstanceTasksRoutes };
export { workflowInstanceEventsRoutes };
export { workflowInstanceAuditEventsRoutes };
export { carePathwayTemplatesRoutes };
export { carePathwayTemplateStepsRoutes };
export { carePathwayTemplateOrderSetTemplatesRoutes };
export { carePlansRoutes };
export { carePlanGoalsRoutes };
export { carePlanTasksRoutes };
export { carePlanChecklistsRoutes };
export { episodesOfCaresRoutes };
export { episodeOfCaresRoutes };
export { episodeOfCareEncountersRoutes };
export { episodeOfCareCarePlansRoutes };
export { episodeOfCareWorkflowInstancesRoutes };
export { tasksRoutes };
export { taskCommentsRoutes };
export { taskAuditEventsRoutes };
export { taskAssignmentsRoutes };
export { alertsRoutes };
export { alertExplanationsRoutes };
export { alertAuditEventsRoutes };
export { handoffsRoutes };
export { handoffTasksRoutes };
export { checklistTemplatesRoutes };
export { checklistTemplateItemsRoutes };
export { checklistInstancesRoutes };
export { checklistInstanceItemsRoutes };
export { escalationPoliciesRoutes };
export { escalationPolicyRulesRoutes };
export { routingRulesRoutes };
export { scheduleTemplatesRoutes };
export { workQueuesRoutes };
export { workQueueTasksRoutes };
export { workQueueAlertsRoutes };
