/**
 * Routes for workQueueTasks
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/workflow-care-pathways.dependencies.js";
import { listWorkQueueTasks } from "@cuur/core/workflow-care-pathways/handlers/index.js";
export async function workQueueTasksRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /work-queues/{id}/tasks
  fastify.get("/work-queues/:id/tasks", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await listWorkQueueTasks(deps.workQueueTaskRepo, orgId);
    return reply.code(200).send(result);
  });

}
