/**
 * List ThresholdProfile DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListThresholdProfileParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /threshold-profile
 */
export const ZListThresholdProfileParamsSchema = z.object({
  category: z.string(),
});

export type ListThresholdProfileParams = z.infer<typeof ZListThresholdProfileParamsSchema>;
