/**
 * DecisionIntelligence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ModelInvocationInput } from "@cuur-cde/core/decision-intelligence/models/model-invocation/index.js";
import { decisionintelligenceSchemas as schemas } from "@cuur-cde/core/decision-intelligence/index.js";
import { z } from "zod";

export function createModelInvocationInput(overrides: Partial<ModelInvocationInput> = {}) {
  const raw = {
    executionTime: overrides.executionTime ?? faker.number.float({ min: 0.0, max: 10000.0 }),
    inputs: overrides.inputs ?? {},
    metadata: overrides.metadata ?? {},
    modelVersionId: overrides.modelVersionId ?? faker.string.alpha(10),
    outputs: overrides.outputs ?? {},
    patientId: overrides.patientId ?? faker.string.alpha(10),
    performanceMetadata: overrides.performanceMetadata ?? {},
    ...overrides,
  };

  return schemas.ModelInvocationInput.parse(raw);
}
