/**
 * AlertExplanation Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/workflow-care-pathways.schemas";

/**
 * Entity: AlertExplanationEntity
 * Description: Represents the AlertExplanation domain model.
 * Source: schemas.AlertExplanation
 */
export const ZAlertExplanationEntitySchema = schemas.AlertExplanation as ZodType<any, any, any>;
export type AlertExplanationEntity = z.infer<typeof ZAlertExplanationEntitySchema>;
