/**
 * Repository interface for CarePlan
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "@cuur-cde/core/_shared";

import type {
  CarePlan,
  ListCarePlansParams,
  UpdateCarePlanRequest
} from "@cuur-cde/core/workflow-care-pathways";
/**
 * CarePlanRepository Interface
 */
export interface CarePlanRepository extends CrudRepository<CarePlan, CarePlan, UpdateCarePlanRequest, string, ListCarePlansParams> {

}
