/**
 * Repository interface for CarePlanGoal
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "@cuur-cde/core/_shared";

import type {
  CarePlanGoal
} from "@cuur-cde/core/workflow-care-pathways";
/**
 * CarePlanGoalRepository Interface
 */
export interface CarePlanGoalRepository extends ReadRepository<CarePlanGoal, string, Record<string, never>> {

}
