/**
 * Repository interface for ChecklistInstance
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { CrudRepository } from "@cuur-cde/core/_shared";

import type {
  ChecklistInstance,
  ChecklistInstanceInput,
  ListChecklistInstancesParams,
  UpdateChecklistInstanceRequest,
} from "@cuur-cde/core/workflow-care-pathways/types";
/**
 * ChecklistInstanceRepository Interface
 */
export interface ChecklistInstanceRepository
  extends CrudRepository<
    ChecklistInstance,
    ChecklistInstanceInput,
    UpdateChecklistInstanceRequest,
    string,
    ListChecklistInstancesParams
  > {}
