/**
 * Repository interface for EpisodeOfCareEncounter
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../../_shared/src/repositories/_base-repository.js";

import type {
  EpisodeOfCareEncounter
} from "../types/index.js";
/**
 * EpisodeOfCareEncounterRepository Interface
 */
export interface EpisodeOfCareEncounterRepository extends ReadRepository<EpisodeOfCareEncounter, string, Record<string, never>> {

}
