/**
 * Repository interface for HandoffTask
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "@cuur-cde/core/_shared";

import type {
  HandoffTask
} from "@cuur-cde/core/workflow-care-pathways/types";
/**
 * HandoffTaskRepository Interface
 */
export interface HandoffTaskRepository extends ReadRepository<HandoffTask, string, Record<string, never>> {

}
