/**
 * ValueSet Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas";

/**
 * Entity: ValueSetEntity
 * Description: Represents the ValueSet domain model.
 * Source: schemas.ValueSet
 */
export const ZValueSetEntitySchema = schemas.ValueSet as ZodType<any, any, any>;
export type ValueSetEntity = z.infer<typeof ZValueSetEntitySchema>;
