/**
 * List ConceptMapMapping DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListConceptMapMappingParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /concept-map-mapping
 */
export const ZListConceptMapMappingParamsSchema = z.object({

});

export type ListConceptMapMappingParams = z.infer<typeof ZListConceptMapMappingParamsSchema>;
