/**
 * DecisionIntelligence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListExplanationFeatureParams, ZListExplanationFeatureParamsSchema } from "@cuur-cde/core/decision-intelligence/models/explanation-feature/index.js";
import { z } from "zod";

export function createListExplanationFeatureParams(overrides: Partial<ListExplanationFeatureParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListExplanationFeatureParamsSchema.parse(raw);
}
