/**
 * List EpisodeOfCareCarePlan DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListEpisodeOfCareCarePlanParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /episode-of-care-care-plan
 */
export const ZListEpisodeOfCareCarePlanParamsSchema = z.object({

});

export type ListEpisodeOfCareCarePlanParams = z.infer<typeof ZListEpisodeOfCareCarePlanParamsSchema>;
