/**
 * IntegrationInteroperability Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { APICredentialInput } from "@cuur-cde/core/integration-interoperability";
import { integrationinteroperabilitySchemas as schemas } from "@cuur-cde/core/integration-interoperability/index.js";
import { z } from "zod";

export function createAPICredentialInput(overrides: Partial<APICredentialInput> = {}) {
  const raw = {
    apiClientId: overrides.apiClientId ?? faker.string.alpha(10),
    credentialType: overrides.credentialType ?? faker.helpers.arrayElement(["api-key", "oauth-client", "certificate"]),
    expiresAt: overrides.expiresAt ?? new Date().toISOString(),
    keyId: overrides.keyId ?? faker.string.alpha(10),
    metadata: overrides.metadata ?? {},
    secret: overrides.secret ?? faker.string.alpha(10),
    ...overrides,
  };

  return schemas.APICredentialInput.parse(raw);
}
