/**
 * EvidenceReview handlers
 *
 * Generated by Handler Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./list-evidence-reviews.handler.js";
export * from "./create-evidence-review.handler.js";
export * from "./get-evidence-review.handler.js";
export * from "./update-evidence-review.handler.js";
export * from "./delete-evidence-review.handler.js";
