/**
 * List OrderSetTemplateItem DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListOrderSetTemplateItemParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /order-set-template-item
 */
export const ZListOrderSetTemplateItemParamsSchema = z.object({

});

export type ListOrderSetTemplateItemParams = z.infer<typeof ZListOrderSetTemplateItemParamsSchema>;
