/**
 * PatientDiagnosticReport Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/patient-clinical-data.schemas.js";

/**
 * Entity: PatientDiagnosticReportEntity
 * Description: Represents the PatientDiagnosticReport domain model.
 * Source: schemas.PatientDiagnosticReport
 */
export const ZPatientDiagnosticReportEntitySchema = schemas.PatientDiagnosticReport as ZodType<any, any, any>;
export type PatientDiagnosticReportEntity = z.infer<typeof ZPatientDiagnosticReportEntitySchema>;
