/**
 * IntegrationInteroperability Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListIntegrationRunLogParams, ZListIntegrationRunLogParamsSchema } from "@cuur-cde/core/integration-interoperability";
import { z } from "zod";

export function createListIntegrationRunLogParams(overrides: Partial<ListIntegrationRunLogParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListIntegrationRunLogParamsSchema.parse(raw);
}
