/**
 * Delete KnowledgePackage DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: DeleteKnowledgePackage DTO
 */
export const ZDeleteKnowledgePackageSchema = z.object({});
export type DeleteKnowledgePackage = z.infer<typeof ZDeleteKnowledgePackageSchema>;
