/**
 * KnowledgePackage schemas
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

// Auto-generated barrel export
export * from "./entity/knowledge-package.entity.js";
export * from "./dto/list-knowledge-package.dto.js";
export * from "./dto/get-knowledge-package.dto.js";
export * from "./dto/delete-knowledge-package.dto.js";
