/**
 * IntegrationInteroperability Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { GetEventSubscriptionPath, ZGetEventSubscriptionPathSchema } from "@cuur/core/integration-interoperability/models/event-subscription/index.js";
import { z } from "zod";

export function createGetEventSubscriptionPath(overrides: Partial<GetEventSubscriptionPath> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZGetEventSubscriptionPathSchema.parse(raw);
}
