/**
 * KnowledgeEvidence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { EvidenceCitationUpdate } from "@cuur/core/knowledge-evidence/models/evidence-citation/index.js";
import { knowledgeevidenceSchemas as schemas } from "@cuur/core/knowledge-evidence/index.js";
import { z } from "zod";

export function createEvidenceCitationUpdate(overrides: Partial<EvidenceCitationUpdate> = {}) {
  const raw = {
    authors: overrides.authors ?? [],
    doi: overrides.doi ?? faker.string.alpha(10),
    journal: overrides.journal ?? faker.string.alpha(10),
    metadata: overrides.metadata ?? {},
    pmid: overrides.pmid ?? faker.string.alpha(10),
    publicationDate: overrides.publicationDate ?? faker.string.alpha(10),
    title: overrides.title ?? faker.string.alpha(10),
    url: overrides.url ?? faker.internet.url(),
    ...overrides,
  };

  return schemas.EvidenceCitationUpdate.parse(raw);
}
