/**
 * List Procedure DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListProcedureParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /procedure
 */
export const ZListProcedureParamsSchema = z.object({
  patientId: z.string(),
  status: z.enum(["preparation", "in-progress", "not-done", "on-hold", "stopped", "completed", "entered-in-error", "unknown"]),
});

export type ListProcedureParams = z.infer<typeof ZListProcedureParamsSchema>;
