/**
 * Task schemas
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

// Auto-generated barrel export
export * from "./entity/task.entity";
export * from "./dto/list-task.dto";
export * from "./dto/create-task.dto";
export * from "./dto/get-task.dto";
export * from "./dto/update-task.dto";
export * from "./dto/delete-task.dto";
