/**
 * List TaskAuditEvent DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListTaskAuditEventParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /task-audit-event
 */
export const ZListTaskAuditEventParamsSchema = z.object({

});

export type ListTaskAuditEventParams = z.infer<typeof ZListTaskAuditEventParamsSchema>;
