/**
 * EvidenceReview Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodTypeAny } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas.js";

/**
 * Entity: EvidenceReviewEntity
 * Description: Represents the EvidenceReview domain model.
 * Source: schemas.EvidenceReview
 */
export const ZEvidenceReviewEntitySchema = schemas.EvidenceReview as ZodTypeAny;
export type EvidenceReviewEntity = z.infer<typeof ZEvidenceReviewEntitySchema>;
