/**
 * List DataImportBatchRecord DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListDataImportBatchRecordParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /data-import-batch-record
 */
export const ZListDataImportBatchRecordParamsSchema = z.object({

});

export type ListDataImportBatchRecordParams = z.infer<typeof ZListDataImportBatchRecordParamsSchema>;
