/**
 * Repository interface for ClinicalRuleVersion
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "@cuur-cde/core/_shared";

import type {
  ClinicalRuleVersion
} from "@cuur-cde/core/knowledge-evidence";
/**
 * ClinicalRuleVersionRepository Interface
 */
export interface ClinicalRuleVersionRepository extends ReadRepository<ClinicalRuleVersion, string, Record<string, never>> {

}
