/**
 * Repository interface for EvidenceReview
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "@cuur-cde/core/_shared";

import type {
  EvidenceReview,
  ListEvidenceReviewsParams,
  UpdateEvidenceReviewRequest
} from "@cuur-cde/core/knowledge-evidence/types";
/**
 * EvidenceReviewRepository Interface
 */
export interface EvidenceReviewRepository extends CrudRepository<EvidenceReview, EvidenceReview, UpdateEvidenceReviewRequest, string, ListEvidenceReviewsParams> {

}
