/**
 * Repository interface for OrderSetTemplate
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "../../../_shared/src/repositories/_base-repository.js";

import type {
  OrderSetTemplate,
  ListOrderSetTemplatesParams,
  UpdateOrderSetTemplateRequest
} from "../types/index.js";
/**
 * OrderSetTemplateRepository Interface
 */
export interface OrderSetTemplateRepository extends CrudRepository<OrderSetTemplate, OrderSetTemplate, UpdateOrderSetTemplateRequest, string, ListOrderSetTemplatesParams> {

}
