/**
 * Repository interface for QuestionnaireTemplateQuestion
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "@cuur-cde/core/_shared";

import type {
  QuestionnaireTemplateQuestion
} from "@cuur-cde/core/knowledge-evidence/types";
/**
 * QuestionnaireTemplateQuestionRepository Interface
 */
export interface QuestionnaireTemplateQuestionRepository extends ReadRepository<QuestionnaireTemplateQuestion, string, Record<string, never>> {

}
