/**
 * Repository interface for ScoringTemplateItem
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  ScoringTemplateItem
} from "../types/index.js";
/**
 * ScoringTemplateItemRepository Interface
 */
export interface ScoringTemplateItemRepository extends ReadRepository<ScoringTemplateItem, string, Record<string, never>> {

}
