/**
 * RiskAssessment schemas
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

// Auto-generated barrel export
export * from "./entity/risk-assessment.entity.js";
export * from "./dto/list-risk-assessment.dto.js";
export * from "./dto/get-risk-assessment.dto.js";
export * from "./dto/delete-risk-assessment.dto.js";
