/**
 * E2E test setup
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * E2E Test Setup - Shared Configuration and Utilities
 */

import jwt from "jsonwebtoken";

// Test Configuration
export const TEST_JWT_SECRET = "test-secret-key-for-e2e-testing";
export const TEST_ORG_ID = "ID_01HQZX3K8PQRS7VN6M9TW1ABJZ"; // Domain-only format (ID_ prefix)
export const TEST_ACCOUNT_ID = "ID_01HQZX3K8PQRS7VN6M9TW1ABJZ"; // Domain-only format (ID_ prefix)
export const TEST_USER_EMAIL = "test@example.com";

// Set JWT_SECRET for auth middleware
process.env.JWT_SECRET = TEST_JWT_SECRET;

/**
 * Generate a valid JWT token for testing
 */
export function generateAuthToken(
  orgId: string = TEST_ORG_ID,
  email: string = TEST_USER_EMAIL
): string {
  return jwt.sign(
    {
      accountId: TEST_ACCOUNT_ID,
      orgIds: [orgId],
      email,
      iat: Math.floor(Date.now() / 1000),
      exp: Math.floor(Date.now() / 1000) + 3600,
    },
    TEST_JWT_SECRET
  );
}

/**
 * Helper to parse JSON response
 */
export function parseJsonResponse(body: string) {
  try {
    return JSON.parse(body);
  } catch {
    return null;
  }
}
