/**
 * Get ChecklistTemplate DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetChecklistTemplatePath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get checklist template by ID
 */
export const ZGetChecklistTemplatePathSchema = z.object({
  checklistTemplateId: z.string(),
});

export type GetChecklistTemplatePath = z.infer<typeof ZGetChecklistTemplatePathSchema>;
