/**
 * Repository interface for FHIRMappingProfile
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  FHIRMappingProfile,
  ListFHIRMappingProfilesParams,
  UpdateFHIRMappingProfileRequest
} from "../types/index.js";
/**
 * FHIRMappingProfileRepository Interface
 */
export interface FHIRMappingProfileRepository extends CrudRepository<FHIRMappingProfile, FHIRMappingProfile, UpdateFHIRMappingProfileRequest, string, ListFHIRMappingProfilesParams> {

}
