/**
 * Routes for careProtocolOrderSets
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/knowledge-evidence.dependencies.js";
import { listCareProtocolOrderSets } from "@cuur/core/knowledge-evidence/handlers/index.js";
export async function careProtocolOrderSetsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /care-protocols/{id}/order-sets
  fastify.get("/care-protocols/:id/order-sets", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await listCareProtocolOrderSets(deps.careProtocolOrderSetRepo, orgId);
    return reply.code(200).send(result);
  });

}
