/**
 * Routes for ontologyTerms
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/knowledge-evidence.dependencies.js";
import { getOntologyTerm } from "@cuur/core/knowledge-evidence/handlers/index.js";
export async function ontologyTermsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /ontology-terms/{id}
  fastify.get("/ontology-terms/:id", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await getOntologyTerm(deps.ontologyTermRepo, orgId);
    return reply.code(200).send(result);
  });

}
