/**
 * Routes for orderSetTemplates
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/knowledge-evidence.dependencies.js";
import { createOrderSetTemplate, deleteOrderSetTemplate, getOrderSetTemplate, listOrderSetTemplates, updateOrderSetTemplate } from "@cuur/core/knowledge-evidence/handlers/index.js";
import type { OrderSetTemplateInput, OrderSetTemplateUpdate } from "@cuur/core/knowledge-evidence/types/index.js";
export async function orderSetTemplatesRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /order-set-templates
  fastify.get("/order-set-templates", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await listOrderSetTemplates(deps.orderSetTemplateRepo, orgId, request.query || {});
    return reply.code(200).send(result);
  });
  // POST /order-set-templates
  fastify.post("/order-set-templates", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await createOrderSetTemplate(deps.orderSetTemplateRepo, orgId, request.body as OrderSetTemplateInput);
    return reply.code(201).send(result);
  });
  // GET /order-set-templates/{id}
  fastify.get("/order-set-templates/:id", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await getOrderSetTemplate(deps.orderSetTemplateRepo, orgId);
    return reply.code(200).send(result);
  });
  // PATCH /order-set-templates/{id}
  fastify.patch("/order-set-templates/:id", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await updateOrderSetTemplate(deps.orderSetTemplateRepo, orgId, request.body as OrderSetTemplateUpdate);
    return reply.code(200).send(result);
  });
  // DELETE /order-set-templates/{id}
  fastify.delete("/order-set-templates/:id", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await deleteOrderSetTemplate(deps.orderSetTemplateRepo, orgId);
    return reply.code(204).send(result);
  });

}
