/**
 * Routes for ruleSetClinicalRules
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/knowledge-evidence.dependencies.js";
import { listRuleSetClinicalRules } from "@cuur/core/knowledge-evidence/handlers/index.js";
export async function ruleSetClinicalRulesRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /rule-sets/{id}/clinical-rules
  fastify.get("/rule-sets/:id/clinical-rules", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await listRuleSetClinicalRules(deps.ruleSetClinicalRuleRepo, orgId);
    return reply.code(200).send(result);
  });

}
