/**
 * Routes for valueSetCodes
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/knowledge-evidence.dependencies.js";
import { listValueSetCodes } from "@cuur/core/knowledge-evidence/handlers/index.js";
export async function valueSetCodesRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /value-sets/{id}/codes
  fastify.get("/value-sets/:id/codes", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await listValueSetCodes(deps.valueSetCodeRepo, orgId);
    return reply.code(200).send(result);
  });

}
