/**
 * DAO adapter for ModelInvocationRepository
 *
 * Generated by Adapter Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  OrgId,
  PaginatedResult,
  PaginationParams,
} from "@cuur/core";
import type {
  ModelInvocationRepository,
} from "@cuur/core/decision-intelligence/repositories/index.js";
import type {
  ModelInvocationInput,
  ModelInvocation, Timestamps,
} from "@cuur/core/decision-intelligence/types/index.js";
import type { DaoClient } from "../shared/dao-client.js";
import { NotFoundError, TransactionManager, handleDatabaseError } from "../shared/index.js";

const DEFAULT_LIMIT = 50;

export class DaoModelInvocationRepository implements ModelInvocationRepository {
  private transactionManager: TransactionManager;

  constructor(private readonly dao: DaoClient) {
    this.transactionManager = new TransactionManager(dao);
  }

  async list(
    orgId: OrgId,
    params?: PaginationParams
  ): Promise<PaginatedResult<ModelInvocation>> {
    try {
      const limit = params?.limit ?? DEFAULT_LIMIT;

      const records = await this.dao.modelInvocation.findMany({
        where: {
          orgId,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
        orderBy: { createdAt: "desc" },
        take: limit,
        ...(params?.cursor ? {
          skip: 1,
          cursor: { id: params.cursor },
        } : {}),
      });

      return {
        items: records.map((r) => this.toDomain(r)),
        nextCursor: records.length === limit
          ? records[records.length - 1]?.id
          : undefined,
        prevCursor: undefined,
      };
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async findById(orgId: OrgId, id: string): Promise<ModelInvocation | null> {
    try {
      const record = await this.dao.modelInvocation.findFirst({
        where: {
          orgId,
          id,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
      });
      return record ? this.toDomain(record) : null;
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async get(orgId: OrgId, id: string): Promise<ModelInvocation | null> {
    const result = await this.findById(orgId, id);
    if (!result) {
      throw new NotFoundError("ModelInvocation", id);
    }
    return result;
  }
  async create(orgId: OrgId, data: ModelInvocation): Promise<ModelInvocation> {
    // Note: Repository interface expects ModelInvocation, but we only use input fields
    // Extract only the input fields to avoid including id, createdAt, updatedAt
    const inputData = data as unknown as ModelInvocationInput;
    try {
      const record = await this.dao.modelInvocation.create({
        data: {
          ...inputData,
          orgId, // Set orgId after spread to ensure it's always set correctly
          
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async createMany(orgId: OrgId, items: Array<ModelInvocationInput>): Promise<ModelInvocation[]> {
    try {
      // Use createMany for better performance
      await this.dao.modelInvocation.createMany({
        data: items.map(item => ({
          ...item,
          orgId,
        })),
        skipDuplicates: true,
      });

      // Fetch created records
      const ids = items.map(item => item.id).filter(Boolean) as string[];
      if (ids.length === 0) {
        return [];
      }

      const records = await this.dao.modelInvocation.findMany({
        where: { id: { in: ids }, orgId },
      });

      return records.map((r) => this.toDomain(r));
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  private toDomain(model: any): ModelInvocation {
    return {
      ...model,
      createdAt: model.createdAt instanceof Date
        ? model.createdAt
        : new Date(model.createdAt),
      updatedAt: model.updatedAt instanceof Date
        ? model.updatedAt
        : model.updatedAt ? new Date(model.updatedAt) : undefined,
    } as ModelInvocation;
  }
}
