/**
 * IntegrationInteroperability Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListFHIRBundleResourceParams, ZListFHIRBundleResourceParamsSchema } from "@cuur/core/integration-interoperability/models/fhirbundle-resource/index.js";
import { z } from "zod";

export function createListFHIRBundleResourceParams(overrides: Partial<ListFHIRBundleResourceParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListFHIRBundleResourceParamsSchema.parse(raw);
}
