/**
 * getChecklistInstance Handler Tests
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * getChecklistInstance Handler Tests
 *
 * Maps to: packages/core/src/workflow-care-pathways/handlers/checklist-instance.handler/get-checklist-instance.handler.ts
 * Strategy: Mock repositories, handler-centric, business rules focus
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { getChecklistInstance as getChecklistInstanceHandler } from "@cuur-cde/core/workflow-care-pathways/handlers/index.js";

import { seedFaker } from "../../factories/faker-helpers.js";

describe("getChecklistInstance - Business Rules", () => {
  const FIXED_DATE = new Date("2025-01-01T00:00:00Z");
  const FAKER_SEED = 12345;
  const TEST_ORG_ID = "ID_01HQZX3K8PQRS7VN6M9TW1ABJZ";

  beforeEach(() => {

    vi.useFakeTimers();
    vi.setSystemTime(FIXED_DATE);
    seedFaker(FAKER_SEED);
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  describe("✅ Happy Path", () => {
    it("should get checklistinstancehandler for org", async () => {
      const result = await getChecklistInstanceHandler(TEST_ORG_ID);

      expect(result.data).toBeDefined();
      expect(Array.isArray(result.data)).toBe(true);
    });
  });

  describe("❌ Error Cases", () => {
    it("should return empty array for org with no checklistinstancehandler", async () => {
      const result = await getChecklistInstanceHandler(TEST_ORG_ID);

      expect(result.data).toBeDefined();
      expect(Array.isArray(result.data)).toBe(true);
      expect(result.data?.length).toBe(0);
    });
  });
});
