/**
 * PatientSummary Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodTypeAny } from "zod";
import { schemas } from "../../../schemas/patient-clinical-data.schemas.js";

/**
 * Entity: PatientSummaryEntity
 * Description: Represents the PatientSummary domain model.
 * Source: schemas.PatientSummary
 */
export const ZPatientSummaryEntitySchema = schemas.PatientSummary as ZodTypeAny;
export type PatientSummaryEntity = z.infer<typeof ZPatientSummaryEntitySchema>;
