/**
 * createEventSubscription Handler Tests
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * createEventSubscription Handler Tests
 *
 * Maps to: packages/core/src/integration-interoperability/handlers/event-subscription.handler/create-event-subscription.handler.ts
 * Strategy: Mock repositories, handler-centric, business rules focus
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { createEventSubscription as createEventSubscriptionHandler } from "@cuur-cde/core/integration-interoperability/handlers/index.js";

import { seedFaker } from "../../factories/faker-helpers.js";

describe("createEventSubscription - Business Rules", () => {
  const FIXED_DATE = new Date("2025-01-01T00:00:00Z");
  const FAKER_SEED = 12345;
  const TEST_ORG_ID = "ID_01HQZX3K8PQRS7VN6M9TW1ABJZ";

  beforeEach(() => {

    vi.useFakeTimers();
    vi.setSystemTime(FIXED_DATE);
    seedFaker(FAKER_SEED);
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  describe("✅ Happy Path", () => {
    it("should create eventsubscriptionhandler with valid data", async () => {
      const input = createEventSubscriptionHandler();

      const result = await createEventSubscriptionHandler(
        TEST_ORG_ID,
        input
      );

      expect(result.data).toBeDefined();
      expect(result.data?.id).toBeDefined();
      expect(result.data?.orgId).toBe(TEST_ORG_ID);
    });
  });

  describe("🔒 Org Isolation", () => {
    it("should enforce org isolation", async () => {
      const input = createEventSubscriptionHandler();

      const result = await createEventSubscriptionHandler(
        TEST_ORG_ID,
        input
      );

      expect(result.data?.orgId).toBe(TEST_ORG_ID);
    });
  });
});
