/**
 * KnowledgeEvidence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { OntologyTermEntity } from "@cuur/core/knowledge-evidence/models/ontology-term/index.js";
import { knowledgeevidenceSchemas as schemas } from "@cuur/core/knowledge-evidence/index.js";
import { z } from "zod";

export function createOntologyTerm(overrides: Partial<OntologyTermEntity> = {}) {
  const raw = {
    code: overrides.code ?? faker.string.alpha(10),
    display: overrides.display ?? faker.string.alpha(10),
    id: overrides.id ?? faker.string.uuid(),
    level: overrides.level ?? faker.number.int({ min: 1, max: 10000 }),
    metadata: overrides.metadata ?? {},
    parentId: overrides.parentId ?? faker.string.alpha(10),
    system: overrides.system ?? faker.string.alpha(10),
    ...overrides,
  };

  return schemas.OntologyTerm.parse(raw);
}

export function ontologyTermBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createOntologyTerm(overrides));
}
