/**
 * Repository interface for ModelInvocation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  Timestamps,
  ListModelInvocationsParams,
  ModelInvocationInput
} from "../types/index.js";
/**
 * ModelInvocationRepository Interface
 */
export interface ModelInvocationRepository extends CreateReadRepository<Timestamps, ModelInvocationInput, string, ListModelInvocationsParams> {

}
