/**
 * DiagnosticReport handlers
 *
 * Generated by Handler Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./list-diagnostic-reports.handler.js";
export * from "./create-diagnostic-report.handler.js";
export * from "./get-diagnostic-report.handler.js";
export * from "./update-diagnostic-report.handler.js";
export * from "./delete-diagnostic-report.handler.js";
