/**
 * Update APIClient DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/integration-interoperability.schemas";

/**
 * DTO: APIClientUpdate
 * Direction: Request Body → Handler → Domain
 * Route: Update API client
 * OpenAPI Source: schemas.APIClientUpdate
 */
export const ZAPIClientUpdateSchema = schemas.APIClientUpdate;
export type APIClientUpdate = z.infer<typeof ZAPIClientUpdateSchema>;
