/**
 * Routes for connectionHealthChecks
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/integration-interoperability.dependencies.js";
import { listConnectionHealthChecks } from "@cuur/core/integration-interoperability/handlers/index.js";
export async function connectionHealthChecksRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /connections/{id}/health-checks
  fastify.get("/connections/:id/health-checks", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await listConnectionHealthChecks(deps.connectionHealthCheckRepo, orgId);
    return reply.code(200).send(result);
  });

}
