/**
 * Routes for integrationRuns
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/integration-interoperability.dependencies.js";
import { createIntegrationRun, getIntegrationRun, listIntegrationRuns } from "@cuur/core/integration-interoperability/handlers/index.js";
import type { IntegrationRunInput } from "@cuur/core/integration-interoperability/types/index.js";
export async function integrationRunsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /integration-runs
  fastify.get("/integration-runs", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await listIntegrationRuns(deps.integrationRunRepo, orgId, request.query || {});
    return reply.code(200).send(result);
  });
  // POST /integration-runs
  fastify.post("/integration-runs", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await createIntegrationRun(deps.integrationRunRepo, orgId, request.body as IntegrationRunInput);
    return reply.code(201).send(result);
  });
  // GET /integration-runs/{id}
  fastify.get("/integration-runs/:id", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await getIntegrationRun(deps.integrationRunRepo, orgId);
    return reply.code(200).send(result);
  });

}
