/**
 * RoutingRule Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/workflow-care-pathways.schemas";

/**
 * Entity: RoutingRuleEntity
 * Description: Represents the RoutingRule domain model.
 * Source: schemas.RoutingRule
 */
export const ZRoutingRuleEntitySchema = schemas.RoutingRule;
export type RoutingRuleEntity = z.infer<typeof ZRoutingRuleEntitySchema>;
