/**
 * Get EvidenceCitation DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetEvidenceCitationPath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get evidence citation by ID
 */
export const ZGetEvidenceCitationPathSchema = z.object({
  evidenceCitationId: z.string(),
});

export type GetEvidenceCitationPath = z.infer<typeof ZGetEvidenceCitationPathSchema>;
