/**
 * Update EvidenceCitation DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas";

/**
 * DTO: EvidenceCitationUpdate
 * Direction: Request Body → Handler → Domain
 * Route: Update evidence citation
 * OpenAPI Source: schemas.EvidenceCitationUpdate
 */
export const ZEvidenceCitationUpdateSchema = schemas.EvidenceCitationUpdate;
export type EvidenceCitationUpdate = z.infer<typeof ZEvidenceCitationUpdateSchema>;
