/**
 * Create RuleSet DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas";

/**
 * DTO: RuleSetInput
 * Direction: Request Body → Handler → Domain
 * Route: Create rule set
 * OpenAPI Source: schemas.RuleSetInput
 */
export const ZRuleSetInputSchema = schemas.RuleSetInput;
export type RuleSetInput = z.infer<typeof ZRuleSetInputSchema>;
