/**
 * Delete RuleSet DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: DeleteRuleSet DTO
 */
export const ZDeleteRuleSetSchema = z.object({});
export type DeleteRuleSet = z.infer<typeof ZDeleteRuleSetSchema>;
