/**
 * RuleSetClinicalRule Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas";

/**
 * Entity: RuleSetClinicalRuleEntity
 * Description: Represents the RuleSetClinicalRule domain model.
 * Source: schemas.RuleSetClinicalRule
 */
export const ZRuleSetClinicalRuleEntitySchema = schemas.RuleSetClinicalRule;
export type RuleSetClinicalRuleEntity = z.infer<typeof ZRuleSetClinicalRuleEntitySchema>;
