/**
 * SimulationScenarioRun Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/decision-intelligence.schemas.js";

/**
 * Entity: SimulationScenarioRunEntity
 * Description: Represents the SimulationScenarioRun domain model.
 * Source: schemas.SimulationScenarioRun
 */
export const ZSimulationScenarioRunEntitySchema = schemas.SimulationScenarioRun as ZodType<any, any, any>;
export type SimulationScenarioRunEntity = z.infer<typeof ZSimulationScenarioRunEntitySchema>;
