/**
 * CareProtocol Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas";

/**
 * Entity: CareProtocolEntity
 * Description: Represents the CareProtocol domain model.
 * Source: schemas.CareProtocol
 */
export const ZCareProtocolEntitySchema = schemas.CareProtocol as ZodType<any, any, any>;
export type CareProtocolEntity = z.infer<typeof ZCareProtocolEntitySchema>;
