/**
 * CarePlan Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/workflow-care-pathways.schemas";

/**
 * Entity: CarePlanEntity
 * Description: Represents the CarePlan domain model.
 * Source: schemas.CarePlan
 */
export const ZCarePlanEntitySchema = schemas.CarePlan as ZodType<any, any, any>;
export type CarePlanEntity = z.infer<typeof ZCarePlanEntitySchema>;
