/**
 * Test utilities barrel export
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * IntegrationInteroperability Service Test Utilities
 *
 * Barrel export for mock repositories and test helpers.
 * Import these in integration-interoperability service tests for consistent mocking.
 *
 * NOTE: Mock repositories are service-specific and live here, NOT in @cuur/factories.
 * @cuur/factories contains only reusable data factories.
 */

// Mock Repositories (service-specific, from mocks/)
export {
  MockFhirmappingProfileRepository,
  MockIntegrationJobRepository,
  MockHlMessageMappingResultRepository,
  MockHlMappingProfileRepository,
  MockConnectionRepository,
  MockExternalSystemIntegrationJobRepository,
  MockEventSubscriptionRepository,
  MockFhirbundleResourceRepository,
  MockDataImportBatchRecordRepository,
  MockIntegrationJobRunRepository,
  MockInterfaceHealthCheckRepository,
  MockFhirbundleRepository,
  MockDataExportBatchFileRepository,
  MockConnectionIntegrationJobRepository,
  MockApiclientCredentialRepository,
  MockConnectionHealthCheckRepository,
  MockExternalSystemRepository,
  MockApiclientUsageMetricRepository,
  MockDataImportBatchRepository,
  MockHlMappingProfileRuleRepository,
  MockIntegrationRunRepository,
  MockExternalSystemConnectionRepository,
  MockApiclientRepository,
  MockExternalSystemEndpointRepository,
  MockDataExportBatchErrorRepository,
  MockDataExportBatchRepository,
  MockApicredentialRepository,
  MockHlMessageSegmentRepository,
  MockIntegrationRunErrorRepository,
  MockFhirmappingProfileRuleRepository,
  MockEventDeliveryRepository,
  MockHlMessageRepository,
  MockInterfaceErrorRepository,
  MockIntegrationRunLogRepository,
  MockDataImportBatchErrorRepository,
  MockEventSubscriptionDeliveryRepository,
} from "./mocks/index.js";

// Test setup helpers
export {
  TEST_JWT_SECRET,
  TEST_ORG_ID,
  TEST_ACCOUNT_ID,
  TEST_USER_EMAIL,
  generateAuthToken,
  parseJsonResponse,
} from "./e2e/setup.js";
