/**
 * Delete EpisodeOfCare DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: DeleteEpisodeOfCare DTO
 */
export const ZDeleteEpisodeOfCareSchema = z.object({});
export type DeleteEpisodeOfCare = z.infer<typeof ZDeleteEpisodeOfCareSchema>;
