/**
 * DecisionIntelligence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListDecisionRequestParams, ZListDecisionRequestParamsSchema } from "@cuur-cde/core/decision-intelligence/models/decision-request/index.js";
import { z } from "zod";

export function createListDecisionRequestParams(overrides: Partial<ListDecisionRequestParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListDecisionRequestParamsSchema.parse(raw);
}
