/**
 * DAO adapter for ClinicalRuleRepository
 *
 * Generated by Adapter Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { OrgId, PaginatedResult, PaginationParams } from "@cuur-cde/core/_shared";
import type { ClinicalRuleRepository } from "@cuur-cde/core/knowledge-evidence";
import type { UpdateClinicalRuleRequest } from "@cuur-cde/core/knowledge-evidence";
import type {
  ClinicalRuleInput,
  ClinicalRuleUpdate,
  ClinicalRule,
  Timestamps,
} from "@cuur-cde/core/knowledge-evidence";
import type { DaoClient } from "@cuur-cde/database";
import { NotFoundError, handleDatabaseError } from "@cuur-cde/core/_shared";

const DEFAULT_LIMIT = 50;

export class DaoClinicalRuleRepository implements ClinicalRuleRepository {

  constructor(
    private readonly dao: DaoClient,
    private readonly tx: TransactionManager
  ) {
  }

  async list(orgId: OrgId, params?: PaginationParams): Promise<PaginatedResult<ClinicalRule>> {
    try {
      const limit = params?.limit ?? DEFAULT_LIMIT;

      const records = await this.dao.clinicalRuleInput.findMany({
        where: {
          orgId,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
        orderBy: { createdAt: "desc" },
        take: limit,
        ...(params && "cursor" in params && params.cursor
          ? {
              skip: 1,
              cursor: { id: params.cursor },
            }
          : {}),
      });

      return {
        items: records.map((r: any) => this.toDomain(r)),
        nextCursor: records.length === limit ? records[records.length - 1]?.id : undefined,
        prevCursor: undefined,
      };
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async findById(orgId: OrgId, id: string): Promise<ClinicalRule | null> {
    try {
      const record = await this.dao.clinicalRuleInput.findFirst({
        where: {
          orgId,
          id,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
      });
      return record ? this.toDomain(record) : null;
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async get(orgId: OrgId, id: string): Promise<ClinicalRule | null> {
    const result = await this.findById(orgId, id);
    if (!result) {
      throw new NotFoundError("ClinicalRule", id);
    }
    return result;
  }
  async create(orgId: OrgId, data: ClinicalRule): Promise<ClinicalRule> {
    // Note: Repository interface expects ClinicalRule, but we only use input fields
    // Extract only the input fields to avoid including id, createdAt, updatedAt
    const inputData = data as unknown as ClinicalRuleInput;
    try {
      const record = await this.dao.clinicalRuleInput.create({
        data: {
          ...data,
          orgId, // Set orgId after spread to ensure it's always set correctly
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async update(orgId: OrgId, id: string, data: UpdateClinicalRuleRequest): Promise<ClinicalRule> {
    try {
      const record = await this.dao.clinicalRuleInput.update({
        where: { id, orgId },
        data: {
          ...data,
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async delete(orgId: OrgId, id: string): Promise<void> {
    try {
      // Soft delete: set deletedAt instead of hard delete
      await this.dao.clinicalRuleInput.update({
        where: { id, orgId },
        data: {
          deletedAt: new Date(),
        },
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async createMany(orgId: OrgId, items: Array<ClinicalRuleInput>): Promise<ClinicalRule[]> {
    try {
      // Use transaction with individual creates to get created records with IDs
      return await this.transactionManager.run(async (tx) => {
        const results: ClinicalRule[] = [];
        for (const item of items) {
                    const record = await tx.clinicalRuleInput.create({
            data: {
              ...item,
              orgId,
            },
          });
          results.push(this.toDomain(record));
        }
        return results;
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async updateMany(
    orgId: OrgId,
    updates: Array<{ id: string; data: ClinicalRuleUpdate }>
  ): Promise<ClinicalRule[]> {
    try {
      // Use transaction for atomic batch updates
      return await this.transactionManager.run(async (tx) => {
        const results: ClinicalRule[] = [];
        for (const { id, data } of updates) {
                    const record = await tx.clinicalRuleInput.update({
            where: { id, orgId },
            data,
          });
          results.push(this.toDomain(record));
        }
        return results;
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async deleteMany(orgId: OrgId, ids: string[]): Promise<void> {
    try {
      // Soft delete: set deletedAt for multiple records
      await this.dao.clinicalRuleInput.updateMany({
        where: {
          id: { in: ids },
          orgId,
        },
        data: {
          deletedAt: new Date(),
        },
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  private toDomain(model: any): ClinicalRule {
    return {
      ...model,
      createdAt: model.createdAt instanceof Date ? model.createdAt : new Date(model.createdAt),
      updatedAt:
        model.updatedAt instanceof Date
          ? model.updatedAt
          : model.updatedAt
          ? new Date(model.updatedAt)
          : undefined,
    } as ClinicalRule;
  }
}
