/**
 * PatientClinicalData Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListEncounterObservationParams, ZListEncounterObservationParamsSchema } from "@cuur/core/patient-clinical-data/models/encounter-observation/index.js";
import { z } from "zod";

export function createListEncounterObservationParams(overrides: Partial<ListEncounterObservationParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListEncounterObservationParamsSchema.parse(raw);
}
