/**
 * KnowledgeEvidence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { DeleteScoringTemplate, ZDeleteScoringTemplateSchema } from "@cuur-cde/core/knowledge-evidence/models/scoring-template/index.js";
import { z } from "zod";

export function createDeleteScoringTemplate(overrides: Partial<DeleteScoringTemplate> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZDeleteScoringTemplateSchema.parse(raw);
}
