/**
 * IntegrationInteroperability Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ConnectionInput } from "@cuur/core/integration-interoperability/models/connection/index.js";
import { integrationinteroperabilitySchemas as schemas } from "@cuur/core/integration-interoperability/index.js";
import { z } from "zod";

export function createConnectionInput(overrides: Partial<ConnectionInput> = {}) {
  const raw = {
    baseUrl: overrides.baseUrl ?? faker.internet.url(),
    credentials: overrides.credentials ?? {},
    description: overrides.description ?? faker.string.alpha(10),
    externalSystemId: overrides.externalSystemId ?? faker.string.alpha(10),
    metadata: overrides.metadata ?? {},
    name: overrides.name ?? faker.word.noun(),
    profile: overrides.profile ?? faker.string.alpha(10),
    protocol: overrides.protocol ?? faker.helpers.arrayElement(["fhir", "hl7", "rest", "soap", "other"]),
    status: overrides.status ?? faker.helpers.arrayElement(["active", "inactive", "error"]),
    ...overrides,
  };

  return schemas.ConnectionInput.parse(raw);
}
