/**
 * Knowledge Evidence Component - Core Export
 *
 * Generated by Index Builder Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

// Import all exports as namespace for named export
import * as Types from "./types/index.js";
import * as Models from "./models/index.js";
import * as Repositories from "./repositories/index.js";
import * as Handlers from "./handlers/index.js";
import { schemas as knowledgeEvidenceSchemas } from "./schemas/knowledge-evidence.schemas.js";
import type * as OpenAPITypes from "./openapi/knowledge-evidence.openapi.types.js";
import * as OpenAPISchemas from "./openapi/knowledge-evidence.zod.schema.js";
import * as Converters from "./utils/knowledge-evidence-converters.js";

// No wildcard re-exports - use the KnowledgeEvidence namespace or import directly from sub-modules
// Example: import { KnowledgeEvidence } from "./index.js" then use KnowledgeEvidence.types.TypeName
// Or: import type { TypeName } from "./types/index.js"

// Named domain export (namespace containing all domain exports)
export const KnowledgeEvidence = {
  types: Types,
  models: Models,
  repositories: Repositories,
  handlers: Handlers,
  schemas: knowledgeEvidenceSchemas,
  openapi: {
    schemas: OpenAPISchemas,
  },
  converters: Converters,
};
