/**
 * Knowledge Evidence Component - Core Export
 *
 * Generated by Index Builder Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

// Import all exports as namespace for named export
import * as Types from "./types/index.js";
import * as Models from "./models/index.js";
import * as Repositories from "./repositories/index.js";
import * as Handlers from "./handlers/index.js";
import { schemas as knowledgeEvidenceSchemas } from "./schemas/knowledge-evidence.schemas.js";
import type * as OpenAPITypes from "./openapi/knowledge-evidence.openapi.types.js";
import * as OpenAPISchemas from "./openapi/knowledge-evidence.zod.schema.js";
import * as Converters from "./utils/knowledge-evidence-converters.js";

// Flat exports (for direct imports)
export * from "./types/index.js";
export * from "./models/index.js";
export * from "./repositories/index.js";
export * from "./handlers/index.js";
export { schemas as knowledgeEvidenceSchemas } from "./schemas/knowledge-evidence.schemas.js";
export type * from "./openapi/knowledge-evidence.openapi.types.js";
export * from "./openapi/knowledge-evidence.zod.schema.js";
export * from "./utils/knowledge-evidence-converters.js";

// Named domain export (namespace containing all domain exports)
export const KnowledgeEvidence = {
  types: Types,
  models: Models,
  repositories: Repositories,
  handlers: Handlers,
  schemas: knowledgeEvidenceSchemas,
  openapi: {
    types: OpenAPITypes,
    schemas: OpenAPISchemas,
  },
  converters: Converters,
};
