/**
 * List PatientDiagnosticReport DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListPatientDiagnosticReportParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /patient-diagnostic-report
 */
export const ZListPatientDiagnosticReportParamsSchema = z.object({

});

export type ListPatientDiagnosticReportParams = z.infer<typeof ZListPatientDiagnosticReportParamsSchema>;
