/**
 * WorkflowInstance Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodTypeAny } from "zod";
import { schemas } from "../../../schemas/workflow-care-pathways.schemas.js";

/**
 * Entity: WorkflowInstanceEntity
 * Description: Represents the WorkflowInstance domain model.
 * Source: schemas.WorkflowInstance
 */
export const ZWorkflowInstanceEntitySchema = schemas.WorkflowInstance as ZodTypeAny;
export type WorkflowInstanceEntity = z.infer<typeof ZWorkflowInstanceEntitySchema>;
