/**
 * EncounterDiagnosticReport Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/patient-clinical-data.schemas.js";

/**
 * Entity: EncounterDiagnosticReportEntity
 * Description: Represents the EncounterDiagnosticReport domain model.
 * Source: schemas.EncounterDiagnosticReport
 */
export const ZEncounterDiagnosticReportEntitySchema = schemas.EncounterDiagnosticReport as ZodType<any, any, any>;
export type EncounterDiagnosticReportEntity = z.infer<typeof ZEncounterDiagnosticReportEntitySchema>;
