/**
 * WorkflowCarePathways Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { DeleteHandoff, ZDeleteHandoffSchema } from "@cuur-cde/core/workflow-care-pathways";
import { z } from "zod";

export function createDeleteHandoff(overrides: Partial<DeleteHandoff> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZDeleteHandoffSchema.parse(raw);
}
