/**
 * WorkflowCarePathways Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { HandoffUpdate } from "@cuur-cde/core/workflow-care-pathways";
import { workflowcarepathwaysSchemas as schemas } from "@cuur-cde/core/workflow-care-pathways/index.js";
import { z } from "zod";

export function createHandoffUpdate(overrides: Partial<HandoffUpdate> = {}) {
  const raw = {
    handoffDate: overrides.handoffDate ?? new Date().toISOString(),
    handoffType: overrides.handoffType ?? faker.helpers.arrayElement(["TYPE_A", "TYPE_B", "TYPE_C", null]),
    metadata: overrides.metadata ?? {},
    notes: overrides.notes ?? faker.string.alpha(10),
    status: overrides.status ?? faker.helpers.arrayElement(["pending", "completed", "cancelled"]),
    ...overrides,
  };

  return schemas.HandoffUpdate.parse(raw);
}
