/**
 * WorkflowCarePathways Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { DeleteAlert, ZDeleteAlertSchema } from "@cuur-cde/core/workflow-care-pathways";
import { z } from "zod";

export function createDeleteAlert(overrides: Partial<DeleteAlert> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZDeleteAlertSchema.parse(raw);
}
