/**
 * List SimulationScenarioRun DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListSimulationScenarioRunParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /simulation-scenario-run
 */
export const ZListSimulationScenarioRunParamsSchema = z.object({

});

export type ListSimulationScenarioRunParams = z.infer<typeof ZListSimulationScenarioRunParamsSchema>;
