/**
 * List KnowledgePackageClinicalRule DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListKnowledgePackageClinicalRuleParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /knowledge-package-clinical-rule
 */
export const ZListKnowledgePackageClinicalRuleParamsSchema = z.object({

});

export type ListKnowledgePackageClinicalRuleParams = z.infer<typeof ZListKnowledgePackageClinicalRuleParamsSchema>;
