/**
 * DecisionIntelligence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { DecisionPolicyInput } from "@cuur-cde/core/decision-intelligence/models/decision-policy/index.js";
import { decisionintelligenceSchemas as schemas } from "@cuur-cde/core/decision-intelligence/index.js";
import { z } from "zod";

export function createDecisionPolicyInput(overrides: Partial<DecisionPolicyInput> = {}) {
  const raw = {
    configuration: overrides.configuration ?? {},
    description: overrides.description ?? faker.string.alpha(10),
    metadata: overrides.metadata ?? {},
    name: overrides.name ?? faker.word.noun(),
    status: overrides.status ?? faker.helpers.arrayElement(["draft", "active", "deprecated"]),
    version: overrides.version ?? faker.string.alpha(10),
    ...overrides,
  };

  return schemas.DecisionPolicyInput.parse(raw);
}
