/**
 * Routes for aPIClientUsageMetrics
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import { extractOrgId } from "../context/org-context.js";
import type { Dependencies } from "../dependencies/integration-interoperability.dependencies.js";
import { listAPIClientUsageMetrics } from "@cuur-cde/core/integration-interoperability/handlers/index.js";
export async function aPIClientUsageMetricsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /api-clients/{id}/usage-metrics (nested route)
  fastify.get("/api-clients/:id/usage-metrics", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listAPIClientUsageMetrics(deps.aPIClientUsageMetricRepo, orgId);
    return reply.code(200).send(result);
  });

  // GET /a-piclient-usage-metrics (flat route for dashboard)
  fastify.get("/a-piclient-usage-metrics", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listAPIClientUsageMetrics(deps.aPIClientUsageMetricRepo, orgId);
    return reply.code(200).send(result);
  });

}
