/**
 * Routes for connectionIntegrationJobs
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import { extractOrgId } from "../extract-org-id.js";
import type { Dependencies } from "../dependencies/integration-interoperability.dependencies.js";
import { listConnectionIntegrationJobs } from "@cuur-cde/core/integration-interoperability/handlers/index.js";
export async function connectionIntegrationJobsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /connections/{id}/integration-jobs (nested route)
  fastify.get("/connections/:id/integration-jobs", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listConnectionIntegrationJobs(deps.connectionIntegrationJobRepo, orgId);
    return reply.code(200).send(result);
  });

  // GET /connection-integration-jobs (flat route for dashboard)
  fastify.get("/connection-integration-jobs", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listConnectionIntegrationJobs(deps.connectionIntegrationJobRepo, orgId);
    return reply.code(200).send(result);
  });

}
