/**
 * Routes for dataImportBatchErrors
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import { extractOrgId } from "../extract-org-id.js";
import type { Dependencies } from "../dependencies/integration-interoperability.dependencies.js";
import { listDataImportBatchErrors } from "@cuur-cde/core/integration-interoperability/handlers/index.js";
export async function dataImportBatchErrorsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /data-import-batches/{id}/errors
  fastify.get("/data-import-batches/:id/errors", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listDataImportBatchErrors(deps.dataImportBatchErrorRepo, orgId);
    return reply.code(200).send(result);
  });

}
