/**
 * Routes for eventSubscriptionDeliveries
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import { extractOrgId } from "../context/org-context.js";
import type { Dependencies } from "../dependencies/integration-interoperability.dependencies.js";
import { listEventSubscriptionDeliveries } from "@cuur-cde/core/integration-interoperability/handlers/index.js";
export async function eventSubscriptionDeliveriesRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /event-subscriptions/{id}/deliveries (nested route)
  fastify.get("/event-subscriptions/:id/deliveries", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listEventSubscriptionDeliveries(deps.eventSubscriptionDeliveryRepo, orgId);
    return reply.code(200).send(result);
  });

  // GET /event-subscription-deliveries (flat route for dashboard)
  fastify.get("/event-subscription-deliveries", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listEventSubscriptionDeliveries(deps.eventSubscriptionDeliveryRepo, orgId);
    return reply.code(200).send(result);
  });

}
