/**
 * Routes for externalSystemConnections
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import { extractOrgId } from "../extract-org-id.js";
import type { Dependencies } from "../dependencies/integration-interoperability.dependencies.js";
import { listExternalSystemConnections } from "@cuur-cde/core/integration-interoperability/handlers/index.js";
export async function externalSystemConnectionsRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /external-systems/{id}/connections (nested route)
  fastify.get("/external-systems/:id/connections", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listExternalSystemConnections(deps.externalSystemConnectionRepo, orgId);
    return reply.code(200).send(result);
  });

  // GET /external-system-connections (flat route for dashboard)
  fastify.get("/external-system-connections", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listExternalSystemConnections(deps.externalSystemConnectionRepo, orgId);
    return reply.code(200).send(result);
  });

}
