/**
 * Routes for fHIRMappingProfileRules
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/integration-interoperability.dependencies.js";
import { listFHIRMappingProfileRules } from "@cuur/core/integration-interoperability/handlers/index.js";
export async function fHIRMappingProfileRulesRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /fhir-mapping-profiles/{id}/rules
  fastify.get("/fhir-mapping-profiles/:id/rules", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listFHIRMappingProfileRules(deps.fHIRMappingProfileRuleRepo, orgId);
    return reply.code(200).send(result);
  });

}
