/**
 * Repository interface for CarePlanTask
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  CarePlanTask
} from "../types/index.js";
/**
 * CarePlanTaskRepository Interface
 */
export interface CarePlanTaskRepository extends ReadRepository<CarePlanTask, string, Record<string, never>> {

}
