/**
 * Repository interface for EscalationPolicy
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  EscalationPolicy,
  ListEscalationPoliciesParams,
  UpdateEscalationPolicyRequest
} from "../types/index.js";
/**
 * EscalationPolicyRepository Interface
 */
export interface EscalationPolicyRepository extends CrudRepository<EscalationPolicy, EscalationPolicy, UpdateEscalationPolicyRequest, string, ListEscalationPoliciesParams> {

}
