/**
 * Repository interface for Handoff
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  Timestamps,
  ListHandoffsParams,
  HandoffInput,
  HandoffUpdate
} from "../types/index.js";
/**
 * HandoffRepository Interface
 */
export interface HandoffRepository extends CrudRepository<Timestamps, HandoffInput, HandoffUpdate, string, ListHandoffsParams> {

}
