/**
 * Repository interface for Task
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  Timestamps,
  ListTasksParams,
  TaskInput,
  TaskUpdate
} from "../types/index.js";
/**
 * TaskRepository Interface
 */
export interface TaskRepository extends CrudRepository<Timestamps, TaskInput, TaskUpdate, string, ListTasksParams> {

}
