/**
 * Repository interface for WorkflowInstance
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  Timestamps,
  ListWorkflowInstancesParams,
  WorkflowInstanceInput,
  WorkflowInstanceUpdate
} from "../types/index.js";
/**
 * WorkflowInstanceRepository Interface
 */
export interface WorkflowInstanceRepository extends CrudRepository<Timestamps, WorkflowInstanceInput, WorkflowInstanceUpdate, string, ListWorkflowInstancesParams> {

}
