/**
 * Repository interface for WorkflowDefinition
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  Timestamps,
  ListWorkflowDefinitionsParams,
  WorkflowDefinitionInput,
  WorkflowDefinitionUpdate
} from "../types/index.js";
/**
 * WorkflowDefinitionRepository Interface
 */
export interface WorkflowDefinitionRepository extends CrudRepository<Timestamps, WorkflowDefinitionInput, WorkflowDefinitionUpdate, string, ListWorkflowDefinitionsParams> {

}
