/**
 * DecisionIntelligence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListRiskAssessmentParams, ZListRiskAssessmentParamsSchema } from "@cuur-cde/core/decision-intelligence/models/risk-assessment/index.js";
import { z } from "zod";

export function createListRiskAssessmentParams(overrides: Partial<ListRiskAssessmentParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListRiskAssessmentParamsSchema.parse(raw);
}
