/**
 * Get SimulationRun DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetSimulationRunPath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get simulation run by ID
 */
export const ZGetSimulationRunPathSchema = z.object({
  simulationRunId: z.string(),
});

export type GetSimulationRunPath = z.infer<typeof ZGetSimulationRunPathSchema>;
