/**
 * Repository interface for DiagnosticReportObservation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "@cuur-cde/core/_shared";

import type {
  DiagnosticReportObservation
} from "@cuur-cde/core/patient-clinical-data/types";
/**
 * DiagnosticReportObservationRepository Interface
 */
export interface DiagnosticReportObservationRepository extends ReadRepository<DiagnosticReportObservation, string, Record<string, never>> {

}
