/**
 * Repository interface for EncounterDiagnosticReport
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  EncounterDiagnosticReport
} from "../types/index.js";
/**
 * EncounterDiagnosticReportRepository Interface
 */
export interface EncounterDiagnosticReportRepository extends ReadRepository<EncounterDiagnosticReport, string, Record<string, never>> {

}
