/**
 * Repository interface for EncounterDiagnosticReport
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "@cuur-cde/core/_shared";

import type {
  EncounterDiagnosticReport
} from "@cuur-cde/core/patient-clinical-data";
/**
 * EncounterDiagnosticReportRepository Interface
 */
export interface EncounterDiagnosticReportRepository extends ReadRepository<EncounterDiagnosticReport, string, Record<string, never>> {

}
