/**
 * Repository interface for MedicationOrder
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "@cuur-cde/core/_shared";

import type {
  MedicationOrder,
  ListMedicationOrdersParams,
  UpdateMedicationOrderRequest
} from "@cuur-cde/core/patient-clinical-data";
/**
 * MedicationOrderRepository Interface
 */
export interface MedicationOrderRepository extends CrudRepository<MedicationOrder, MedicationOrder, UpdateMedicationOrderRequest, string, ListMedicationOrdersParams> {

}
