/**
 * Repository interface for Observation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "@cuur-cde/core/_shared";

import type {
  Observation,
  ListObservationsParams,
  UpdateObservationRequest
} from "@cuur-cde/core/patient-clinical-data/types";
/**
 * ObservationRepository Interface
 */
export interface ObservationRepository extends CrudRepository<Observation, Observation, UpdateObservationRequest, string, ListObservationsParams> {

}
