/**
 * Repository interface for PatientVital
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../../_shared/src/repositories/_base-repository.js";

import type {
  PatientVital
} from "../types/index.js";
/**
 * PatientVitalRepository Interface
 */
export interface PatientVitalRepository extends ReadRepository<PatientVital, string, Record<string, never>> {

}
