/**
 * Repository interface for PatientDiagnosticReport
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../../_shared/src/repositories/_base-repository.js";

import type {
  PatientDiagnosticReport
} from "../types/index.js";
/**
 * PatientDiagnosticReportRepository Interface
 */
export interface PatientDiagnosticReportRepository extends ReadRepository<PatientDiagnosticReport, string, Record<string, never>> {

}
