/**
 * Update MedicationStatement DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/patient-clinical-data.schemas";

/**
 * DTO: MedicationStatementUpdate
 * Direction: Request Body → Handler → Domain
 * Route: Update medication statement
 * OpenAPI Source: schemas.MedicationStatementUpdate
 */
export const ZMedicationStatementUpdateSchema = schemas.MedicationStatementUpdate;
export type MedicationStatementUpdate = z.infer<typeof ZMedicationStatementUpdateSchema>;
