/**
 * Get EvidenceReview DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetEvidenceReviewPath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get evidence review by ID
 */
export const ZGetEvidenceReviewPathSchema = z.object({
  evidenceReviewId: z.string(),
});

export type GetEvidenceReviewPath = z.infer<typeof ZGetEvidenceReviewPathSchema>;
