/**
 * Get Procedure DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetProcedurePath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get procedure by ID
 */
export const ZGetProcedurePathSchema = z.object({
  procedureId: z.string(),
});

export type GetProcedurePath = z.infer<typeof ZGetProcedurePathSchema>;
