/**
 * WorkflowCarePathways Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListWorkQueueTaskParams, ZListWorkQueueTaskParamsSchema } from "@cuur/core/workflow-care-pathways/models/work-queue-task/index.js";
import { z } from "zod";

export function createListWorkQueueTaskParams(overrides: Partial<ListWorkQueueTaskParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListWorkQueueTaskParamsSchema.parse(raw);
}
