/**
 * Get OntologyTerm DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetOntologyTermPath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get ontology term by ID
 */
export const ZGetOntologyTermPathSchema = z.object({
  ontologyTermId: z.string(),
});

export type GetOntologyTermPath = z.infer<typeof ZGetOntologyTermPathSchema>;
