/**
 * DecisionRequestExplanation Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/decision-intelligence.schemas.js";

/**
 * Entity: DecisionRequestExplanationEntity
 * Description: Represents the DecisionRequestExplanation domain model.
 * Source: schemas.DecisionRequestExplanation
 */
export const ZDecisionRequestExplanationEntitySchema = schemas.DecisionRequestExplanation as ZodType<any, any, any>;
export type DecisionRequestExplanationEntity = z.infer<typeof ZDecisionRequestExplanationEntitySchema>;
