/**
 * IntegrationInteroperability Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListInterfaceErrorParams, ZListInterfaceErrorParamsSchema } from "@cuur/core/integration-interoperability/models/interface-error/index.js";
import { z } from "zod";

export function createListInterfaceErrorParams(overrides: Partial<ListInterfaceErrorParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListInterfaceErrorParamsSchema.parse(raw);
}
