/**
 * DecisionSessionAlert Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodTypeAny } from "zod";
import { schemas } from "../../../schemas/decision-intelligence.schemas.js";

/**
 * Entity: DecisionSessionAlertEntity
 * Description: Represents the DecisionSessionAlert domain model.
 * Source: schemas.DecisionSessionAlert
 */
export const ZDecisionSessionAlertEntitySchema = schemas.DecisionSessionAlert as ZodTypeAny;
export type DecisionSessionAlertEntity = z.infer<typeof ZDecisionSessionAlertEntitySchema>;
