/**
 * Update SimulationScenario DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/decision-intelligence.schemas";

/**
 * DTO: SimulationScenarioUpdate
 * Direction: Request Body → Handler → Domain
 * Route: Update simulation scenario
 * OpenAPI Source: schemas.SimulationScenarioUpdate
 */
export const ZSimulationScenarioUpdateSchema = schemas.SimulationScenarioUpdate;
export type SimulationScenarioUpdate = z.infer<typeof ZSimulationScenarioUpdateSchema>;
