/**
 * IntegrationInteroperability Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { HL7MappingProfileUpdate } from "@cuur-cde/core/integration-interoperability/models/hl7mapping-profile/index.js";
import { integrationinteroperabilitySchemas as schemas } from "@cuur-cde/core/integration-interoperability/index.js";
import { z } from "zod";

export function createHL7MappingProfileUpdate(overrides: Partial<HL7MappingProfileUpdate> = {}) {
  const raw = {
    description: overrides.description ?? faker.string.alpha(10),
    messageType: overrides.messageType ?? faker.helpers.arrayElement(["TYPE_A", "TYPE_B", "TYPE_C", null]),
    metadata: overrides.metadata ?? {},
    name: overrides.name ?? faker.word.noun(),
    version: overrides.version ?? faker.string.alpha(10),
    ...overrides,
  };

  return schemas.HL7MappingProfileUpdate.parse(raw);
}
