/**
 * KnowledgeEvidence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListModelDefinitionVersionParams, ZListModelDefinitionVersionParamsSchema } from "@cuur/core/knowledge-evidence/models/model-definition-version/index.js";
import { z } from "zod";

export function createListModelDefinitionVersionParams(overrides: Partial<ListModelDefinitionVersionParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListModelDefinitionVersionParamsSchema.parse(raw);
}
