/**
 * DAO adapter for ChecklistInstanceRepository
 *
 * Generated by Adapter Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { OrgId, PaginatedResult, PaginationParams } from "@cuur/core";
import type { ChecklistInstanceRepository } from "@cuur/core/workflow-care-pathways/repositories/index.js";
import type {
  ChecklistInstanceInput,
  ChecklistInstanceUpdate,
  UpdateChecklistInstanceRequest,
  ChecklistInstance,
  Timestamps,
} from "@cuur/core/workflow-care-pathways/types/index.js";
import type { DaoClient } from "../shared/dao-client.js";
import { NotFoundError, TransactionManager, handleDatabaseError } from "../shared/index.js";

const DEFAULT_LIMIT = 50;

export class DaoChecklistInstanceRepository implements ChecklistInstanceRepository {
  private transactionManager: TransactionManager;

  constructor(private readonly dao: DaoClient) {
    this.transactionManager = new TransactionManager(dao);
  }

  async list(orgId: OrgId, params?: PaginationParams): Promise<PaginatedResult<ChecklistInstance>> {
    try {
      const limit = params?.limit ?? DEFAULT_LIMIT;

      const records = await this.dao.checklistInstance.findMany({
        where: {
          orgId,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
        orderBy: { createdAt: "desc" },
        take: limit,
        ...(params && "cursor" in params && params.cursor
          ? {
              skip: 1,
              cursor: { id: params.cursor },
            }
          : {}),
      });

      return {
        items: records.map((r: any) => this.toDomain(r)),
        nextCursor: records.length === limit ? records[records.length - 1]?.id : undefined,
        prevCursor: undefined,
      };
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async findById(orgId: OrgId, id: string): Promise<ChecklistInstance | null> {
    try {
      const record = await this.dao.checklistInstance.findFirst({
        where: {
          orgId,
          id,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
      });
      return record ? this.toDomain(record) : null;
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async get(orgId: OrgId, id: string): Promise<ChecklistInstance | null> {
    const result = await this.findById(orgId, id);
    if (!result) {
      throw new NotFoundError("ChecklistInstance", id);
    }
    return result;
  }
  async create(orgId: OrgId, data: ChecklistInstanceInput): Promise<ChecklistInstance> {
    try {
      const record = await this.dao.checklistInstance.create({
        data: {
          ...data,
          orgId,
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async update(
    orgId: OrgId,
    id: string,
    data: UpdateChecklistInstanceRequest
  ): Promise<ChecklistInstance> {
    try {
      const record = await this.dao.checklistInstance.update({
        where: { id, orgId },
        data: {
          ...data,
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async delete(orgId: OrgId, id: string): Promise<void> {
    try {
      // Soft delete: set deletedAt instead of hard delete
      await this.dao.checklistInstance.update({
        where: { id, orgId },
        data: {
          deletedAt: new Date(),
        },
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async createMany(
    orgId: OrgId,
    items: Array<ChecklistInstanceInput>
  ): Promise<ChecklistInstance[]> {
    try {
      // Use transaction with individual creates to get created records with IDs
      return await this.transactionManager.executeInTransaction(async (tx) => {
        const results: ChecklistInstance[] = [];
        for (const item of items) {
          const record = await tx.checklistInstance.create({
            data: {
              ...item,
              orgId,
            },
          });
          results.push(this.toDomain(record));
        }
        return results;
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async updateMany(
    orgId: OrgId,
    updates: Array<{ id: string; data: ChecklistInstanceUpdate }>
  ): Promise<ChecklistInstance[]> {
    try {
      // Use transaction for atomic batch updates
      return await this.transactionManager.executeInTransaction(async (tx) => {
        const results: ChecklistInstance[] = [];
        for (const { id, data } of updates) {
          const record = await tx.checklistInstance.update({
            where: { id, orgId },
            data,
          });
          results.push(this.toDomain(record));
        }
        return results;
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async deleteMany(orgId: OrgId, ids: string[]): Promise<void> {
    try {
      // Soft delete: set deletedAt for multiple records
      await this.dao.checklistInstance.updateMany({
        where: {
          id: { in: ids },
          orgId,
        },
        data: {
          deletedAt: new Date(),
        },
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  private toDomain(model: any): ChecklistInstance {
    return {
      ...model,
      createdAt: model.createdAt instanceof Date ? model.createdAt : new Date(model.createdAt),
      updatedAt:
        model.updatedAt instanceof Date
          ? model.updatedAt
          : model.updatedAt
          ? new Date(model.updatedAt)
          : undefined,
    } as ChecklistInstance;
  }
}
