/**
 * DAO adapter for EpisodeOfCareCarePlanRepository
 *
 * Generated by Adapter Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  OrgId,
  PaginatedResult,
  PaginationParams,
} from "@cuur-cde/core/_shared/src/repositories/_base-repository.js";
import type {
  EpisodeOfCareCarePlanRepository,
} from "@cuur-cde/core/workflow-care-pathways/repositories/index.js";
import type {
  EpisodeOfCareCarePlan,
} from "@cuur-cde/core/workflow-care-pathways/types/index.js";
import type { DaoClient } from "../db/dao-client.js";
import { NotFoundError, TransactionManager, handleDatabaseError } from "../utils/repository-helpers.js";

const DEFAULT_LIMIT = 50;

export class DaoEpisodeOfCareCarePlanRepository implements EpisodeOfCareCarePlanRepository {
  private transactionManager: TransactionManager;

  constructor(private readonly dao: DaoClient) {
    this.transactionManager = new TransactionManager(dao);
  }

  async list(
    orgId: OrgId,
    params?: PaginationParams
  ): Promise<PaginatedResult<EpisodeOfCareCarePlan>> {
    try {
      const limit = params?.limit ?? DEFAULT_LIMIT;

      const records = await this.dao.episodeOfCareCarePlan.findMany({
        where: {
          orgId,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
        orderBy: { createdAt: "desc" },
        take: limit,
        ...(params && 'cursor' in params && params.cursor ? {
          skip: 1,
          cursor: { id: params.cursor },
        } : {}),
      });

      return {
        items: records.map((r: any) => this.toDomain(r)),
        nextCursor: records.length === limit
          ? records[records.length - 1]?.id
          : undefined,
        prevCursor: undefined,
      };
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async findById(orgId: OrgId, id: string): Promise<EpisodeOfCareCarePlan | null> {
    try {
      const record = await this.dao.episodeOfCareCarePlan.findFirst({
        where: {
          orgId,
          id,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
      });
      return record ? this.toDomain(record) : null;
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async get(orgId: OrgId, id: string): Promise<EpisodeOfCareCarePlan | null> {
    const result = await this.findById(orgId, id);
    if (!result) {
      throw new NotFoundError("EpisodeOfCareCarePlan", id);
    }
    return result;
  }
  private toDomain(model: any): EpisodeOfCareCarePlan {
    return {
      ...model,
      createdAt: model.createdAt instanceof Date
        ? model.createdAt
        : new Date(model.createdAt),
      updatedAt: model.updatedAt instanceof Date
        ? model.updatedAt
        : model.updatedAt ? new Date(model.updatedAt) : undefined,
    } as EpisodeOfCareCarePlan;
  }
}
