/**
 * DAO adapter for WorkflowDefinitionRepository
 *
 * Generated by Adapter Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { OrgId, PaginatedResult, PaginationParams } from "@cuur-cde/core/_shared/src/repositories/_base-repository.js";
import type { WorkflowDefinitionRepository } from "@cuur-cde/core/workflow-care-pathways/repositories/index.js";
import type {
  WorkflowDefinition,
  Timestamps,
  WorkflowDefinitionInput,
  WorkflowDefinitionUpdate,
  UpdateWorkflowDefinitionRequest,
} from "@cuur-cde/core/workflow-care-pathways/types/index.js";
import type { DaoClient } from "../db/dao-client.js";
import { NotFoundError, TransactionManager, handleDatabaseError } from "../utils/repository-helpers.js";

const DEFAULT_LIMIT = 50;

export class DaoWorkflowDefinitionRepository implements WorkflowDefinitionRepository {
  private transactionManager: TransactionManager;

  constructor(private readonly dao: DaoClient) {
    this.transactionManager = new TransactionManager(dao);
  }

  async list(
    orgId: OrgId,
    params?: PaginationParams
  ): Promise<PaginatedResult<WorkflowDefinition>> {
    try {
      const limit = params?.limit ?? DEFAULT_LIMIT;

      const records = await this.dao.workflowDefinition.findMany({
        where: {
          orgId,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
        orderBy: { createdAt: "desc" },
        take: limit,
        ...(params && "cursor" in params && params.cursor
          ? {
              skip: 1,
              cursor: { id: params.cursor },
            }
          : {}),
      });

      return {
        items: records.map((r: any) => this.toDomain(r)),
        nextCursor: records.length === limit ? records[records.length - 1]?.id : undefined,
        prevCursor: undefined,
      };
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async findById(orgId: OrgId, id: string): Promise<WorkflowDefinition | null> {
    try {
      const record = await this.dao.workflowDefinition.findFirst({
        where: {
          orgId,
          id,
          deletedAt: null, // Soft delete filter - only return non-deleted records
        },
      });
      return record ? this.toDomain(record) : null;
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async get(orgId: OrgId, id: string): Promise<WorkflowDefinition | null> {
    const result = await this.findById(orgId, id);
    if (!result) {
      throw new NotFoundError("WorkflowDefinition", id);
    }
    return result;
  }
  async create(orgId: OrgId, data: WorkflowDefinition): Promise<WorkflowDefinition> {
    // Note: Repository interface expects WorkflowDefinition, but we only use input fields
    // Extract only the input fields to avoid including id, createdAt, updatedAt
    const inputData = data as unknown as WorkflowDefinitionInput;
    try {
      const record = await this.dao.workflowDefinition.create({
        data: {
          ...data,
          orgId, // Set orgId after spread to ensure it's always set correctly
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async update(
    orgId: OrgId,
    id: string,
    data: UpdateWorkflowDefinitionRequest
  ): Promise<WorkflowDefinition> {
    try {
      const record = await this.dao.workflowDefinition.update({
        where: { id, orgId },
        data: {
          ...data,
        },
      });
      return this.toDomain(record);
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async delete(orgId: OrgId, id: string): Promise<void> {
    try {
      // Soft delete: set deletedAt instead of hard delete
      await this.dao.workflowDefinition.update({
        where: { id, orgId },
        data: {
          deletedAt: new Date(),
        },
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async createMany(
    orgId: OrgId,
    items: Array<WorkflowDefinitionInput>
  ): Promise<WorkflowDefinition[]> {
    try {
      // Use transaction with individual creates to get created records with IDs
      return await this.transactionManager.executeInTransaction(async (tx) => {
        const results: WorkflowDefinition[] = [];
        for (const item of items) {
          const record = await tx.workflowDefinition.create({
            data: {
              ...item,
              orgId,
            },
          });
          results.push(this.toDomain(record));
        }
        return results;
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async updateMany(
    orgId: OrgId,
    updates: Array<{ id: string; data: WorkflowDefinitionUpdate }>
  ): Promise<WorkflowDefinition[]> {
    try {
      // Use transaction for atomic batch updates
      return await this.transactionManager.executeInTransaction(async (tx) => {
        const results: WorkflowDefinition[] = [];
        for (const { id, data } of updates) {
          const record = await tx.workflowDefinition.update({
            where: { id, orgId },
            data,
          });
          results.push(this.toDomain(record));
        }
        return results;
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  async deleteMany(orgId: OrgId, ids: string[]): Promise<void> {
    try {
      // Soft delete: set deletedAt for multiple records
      await this.dao.workflowDefinition.updateMany({
        where: {
          id: { in: ids },
          orgId,
        },
        data: {
          deletedAt: new Date(),
        },
      });
    } catch (error) {
      handleDatabaseError(error);
      throw error;
    }
  }
  private toDomain(model: any): WorkflowDefinition {
    return {
      ...model,
      createdAt: model.createdAt instanceof Date ? model.createdAt : new Date(model.createdAt),
      updatedAt:
        model.updatedAt instanceof Date
          ? model.updatedAt
          : model.updatedAt
          ? new Date(model.updatedAt)
          : undefined,
    } as WorkflowDefinition;
  }
}
