/**
 * Routes for scheduleTemplates
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/workflow-care-pathways.dependencies.js";
import { createScheduleTemplate, deleteScheduleTemplate, getScheduleTemplate, listScheduleTemplates, updateScheduleTemplate } from "@cuur/core/workflow-care-pathways/handlers/index.js";
import type { ScheduleTemplateInput, ScheduleTemplateUpdate } from "@cuur/core/workflow-care-pathways/types/index.js";
export async function scheduleTemplatesRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /schedule-templates
  fastify.get("/schedule-templates", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await listScheduleTemplates(deps.scheduleTemplateRepo, orgId, request.query || {});
    return reply.code(200).send(result);
  });
  // POST /schedule-templates
  fastify.post("/schedule-templates", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await createScheduleTemplate(deps.scheduleTemplateRepo, orgId, request.body as ScheduleTemplateInput);
    return reply.code(201).send(result);
  });
  // GET /schedule-templates/{id}
  fastify.get("/schedule-templates/:id", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await getScheduleTemplate(deps.scheduleTemplateRepo, orgId);
    return reply.code(200).send(result);
  });
  // PATCH /schedule-templates/{id}
  fastify.patch("/schedule-templates/:id", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await updateScheduleTemplate(deps.scheduleTemplateRepo, orgId, request.body as ScheduleTemplateUpdate);
    return reply.code(200).send(result);
  });
  // DELETE /schedule-templates/{id}
  fastify.delete("/schedule-templates/:id", async (request, reply) => {
    const orgId = (request as any).orgId || (request.headers as any)['x-org-id'] || '';
    const result = await deleteScheduleTemplate(deps.scheduleTemplateRepo, orgId);
    return reply.code(204).send(result);
  });

}
