/**
 * KnowledgeEvidence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { DeleteEvidenceCitation, ZDeleteEvidenceCitationSchema } from "@cuur-cde/core/knowledge-evidence";
import { z } from "zod";

export function createDeleteEvidenceCitation(overrides: Partial<DeleteEvidenceCitation> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZDeleteEvidenceCitationSchema.parse(raw);
}
