/**
 * ExternalSystem schemas
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

// Auto-generated barrel export
export * from "./entity/external-system.entity";
export * from "./dto/list-external-system.dto";
export * from "./dto/create-external-system.dto";
export * from "./dto/get-external-system.dto";
export * from "./dto/update-external-system.dto";
export * from "./dto/delete-external-system.dto";
