/**
 * DecisionIntelligence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { DecisionMetricSnapshotInput } from "@cuur-cde/core/decision-intelligence";
import { decisionintelligenceSchemas as schemas } from "@cuur-cde/core/decision-intelligence/index.js";
import { z } from "zod";

export function createDecisionMetricSnapshotInput(overrides: Partial<DecisionMetricSnapshotInput> = {}) {
  const raw = {
    decisionPolicyId: overrides.decisionPolicyId ?? faker.string.alpha(10),
    metadata: overrides.metadata ?? {},
    metrics: overrides.metrics ?? {},
    modelDefinitionId: overrides.modelDefinitionId ?? faker.string.alpha(10),
    snapshotDate: overrides.snapshotDate ?? new Date().toISOString(),
    ...overrides,
  };

  return schemas.DecisionMetricSnapshotInput.parse(raw);
}
