/**
 * Delete ScoringTemplate DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: DeleteScoringTemplate DTO
 */
export const ZDeleteScoringTemplateSchema = z.object({});
export type DeleteScoringTemplate = z.infer<typeof ZDeleteScoringTemplateSchema>;
