/**
 * List ScoringTemplate DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListScoringTemplateParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /scoring-template
 */
export const ZListScoringTemplateParamsSchema = z.object({
  category: z.string(),
});

export type ListScoringTemplateParams = z.infer<typeof ZListScoringTemplateParamsSchema>;
