/**
 * WorkflowCarePathways Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { GetEscalationPolicyPath, ZGetEscalationPolicyPathSchema } from "@cuur/core/workflow-care-pathways/models/escalation-policy/index.js";
import { z } from "zod";

export function createGetEscalationPolicyPath(overrides: Partial<GetEscalationPolicyPath> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZGetEscalationPolicyPathSchema.parse(raw);
}
