/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description User role within an organization - used by Identity, Compliance */
        Role: {
            id: string;
            /** @enum {string} */
            name: "ADMIN" | "OPERATIONS" | "COMPLIANCE" | "FINANCE" | "PROJECT_MANAGER" | "INVESTOR" | "VIEWER";
            /**
             * @description List of permission strings
             * @example [
             *       "read:projects",
             *       "write:offerings",
             *       "approve:subscriptions"
             *     ]
             */
            permissions: string[];
            orgId?: components["schemas"]["OrgId"];
        };
        /** @description User account in the identity system */
        Account: {
            id: components["schemas"]["AccountId"];
            /** Format: email */
            email: string;
            status: components["schemas"]["AccountStatus"];
            createdAt: components["schemas"]["Timestamp"];
            lastLoginAt?: components["schemas"]["NullableTimestamp"];
            mfaEnabled?: boolean;
            emailVerified?: boolean;
        };
        /** @description Organization entity - used by Identity, Compliance, all tenant-scoped services */
        Org: {
            id: components["schemas"]["OrgId"];
            /**
             * @description Legal registered name
             * @example Acme Investment Bank Ltd
             */
            legalName: string;
            /**
             * @description ISO 3166-1 alpha-2 country code
             * @example US
             */
            country?: string;
            /**
             * @description Organization classification
             * @enum {string}
             */
            type?: "ISSUER" | "SPV" | "CUSTODIAN" | "INVESTOR" | "PLATFORM";
            status: components["schemas"]["OrgStatus"];
            /**
             * @description Verified domain name
             * @example acme-bank.com
             */
            domain?: string;
            createdAt?: components["schemas"]["Timestamp"];
            updatedAt?: components["schemas"]["Timestamp"];
        };
        /** @description API key for programmatic access */
        ApiKey: {
            id: string;
            accountId: components["schemas"]["AccountId"];
            orgId: components["schemas"]["OrgId"];
            /** @description Human-readable name for the API key */
            name: string;
            /**
             * @description First 8 characters of the key (for identification)
             * @example key_abcd
             */
            keyPreview?: string;
            status: components["schemas"]["ApiKeyStatus"];
            /** @description OAuth2 scopes granted to this API key */
            scopes?: string[];
            expiresAt?: components["schemas"]["NullableTimestamp"];
            createdAt: components["schemas"]["Timestamp"];
            lastUsedAt?: components["schemas"]["NullableTimestamp"];
        };
        /** @description Optional timestamp (RFC3339 in UTC or null) */
        NullableTimestamp: components["schemas"]["Timestamp"] | null;
        /**
         * @description API key lifecycle status
         * @enum {string}
         */
        ApiKeyStatus: "ACTIVE" | "REVOKED" | "EXPIRED";
        /**
         * @description Organization status
         * @enum {string}
         */
        OrgStatus: "ACTIVE" | "SUSPENDED" | "CLOSED";
        /**
         * Format: date-time
         * @description RFC3339 timestamp in UTC (Zulu) unless explicitly stated otherwise
         * @example 2025-10-22T10:30:00Z
         */
        Timestamp: string;
        /**
         * @description Current status of an account
         * @enum {string}
         */
        AccountStatus: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "PENDING_VERIFICATION" | "CLOSED";
        /**
         * @description Account identifier (prefixed ULID)
         *
         *     Format: `acc_` + 26-character base32 ULID
         *     - Length: 30 characters
         *     - Sortable: Lexicographically ordered by creation time
         *     - URL-safe: No encoding needed
         * @example ID_01HQZX3K8PQRS7VN6M9TW1ABJR
         */
        AccountId: string;
        /**
         * @description Organization identifier (prefixed ULID)
         *
         *     Format: `org_` + 26-character base32 ULID
         *     - Length: 30 characters
         *     - Sortable: Lexicographically ordered by creation time
         *     - URL-safe: No encoding needed
         *     - Human-recognizable: Prefix indicates entity type
         * @example ID_01HQZX3K8PQRS7VN6M9TW1ABJY
         */
        OrgId: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Account = components["schemas"]["Account"];
export type AccountId = components["schemas"]["AccountId"];
export type AccountStatus = components["schemas"]["AccountStatus"];
export type ApiKey = components["schemas"]["ApiKey"];
export type ApiKeyStatus = components["schemas"]["ApiKeyStatus"];
export type NullableTimestamp = components["schemas"]["NullableTimestamp"];
export type Org = components["schemas"]["Org"];
export type OrgId = components["schemas"]["OrgId"];
export type OrgStatus = components["schemas"]["OrgStatus"];
export type Role = components["schemas"]["Role"];
export type Timestamp = components["schemas"]["Timestamp"];
export type operations = Record<string, never>;
