/**
 * WorkflowCarePathways Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { DeleteEscalationPolicy, ZDeleteEscalationPolicySchema } from "@cuur-cde/core/workflow-care-pathways/models/escalation-policy/index.js";
import { z } from "zod";

export function createDeleteEscalationPolicy(overrides: Partial<DeleteEscalationPolicy> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZDeleteEscalationPolicySchema.parse(raw);
}
