/**
 * listEpisodeOfCareCarePlans Handler Tests
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * listEpisodeOfCareCarePlans Handler Tests
 *
 * Maps to: packages/core/src/workflow-care-pathways/handlers/episode-of-care-care-plans.handler/list-episode-of-care-care-plans.handler.ts
 * Strategy: Mock repositories, handler-centric, business rules focus
 */

import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { listEpisodeOfCareCarePlans as listEpisodeOfCareCarePlansHandler } from "@cuur/core/workflow-care-pathways/handlers/index.js";

import { seedFaker,
    createEpisodeOfCareCarePlansHandler } from "@quub/factories";

describe("listEpisodeOfCareCarePlans - Business Rules", () => {
  const FIXED_DATE = new Date("2025-01-01T00:00:00Z");
  const FAKER_SEED = 12345;
  const TEST_ORG_ID = "ID_01HQZX3K8PQRS7VN6M9TW1ABJZ";

  beforeEach(() => {

    vi.useFakeTimers();
    vi.setSystemTime(FIXED_DATE);
    seedFaker(FAKER_SEED);
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  describe("✅ Happy Path", () => {
    it("should list episodeofcarecareplanshandlers", async () => {
      const result = await listEpisodeOfCareCarePlansHandler(TEST_ORG_ID);

      expect(result.data).toBeDefined();
      expect(Array.isArray(result.data)).toBe(true);
    });
  });
});
