/**
 * Get Handoff DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: GetHandoffPath
 * Direction: Path Parameters → Handler → Domain
 * Route: Get handoff by ID
 */
export const ZGetHandoffPathSchema = z.object({
  handoffId: z.string(),
});

export type GetHandoffPath = z.infer<typeof ZGetHandoffPathSchema>;
