/**
 * EpisodeOfCareCarePlan Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/workflow-care-pathways.schemas";

/**
 * Entity: EpisodeOfCareCarePlanEntity
 * Description: Represents the EpisodeOfCareCarePlan domain model.
 * Source: schemas.EpisodeOfCareCarePlan
 */
export const ZEpisodeOfCareCarePlanEntitySchema = schemas.EpisodeOfCareCarePlan;
export type EpisodeOfCareCarePlanEntity = z.infer<typeof ZEpisodeOfCareCarePlanEntitySchema>;
