/**
 * Delete ChecklistInstance DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: DeleteChecklistInstance DTO
 */
export const ZDeleteChecklistInstanceSchema = z.object({});
export type DeleteChecklistInstance = z.infer<typeof ZDeleteChecklistInstanceSchema>;
