/**
 * Update DataExportBatch DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
import { schemas } from "../../../schemas/integration-interoperability.schemas";

/**
 * DTO: DataExportBatchUpdate
 * Direction: Request Body → Handler → Domain
 * Route: Update data export batch
 * OpenAPI Source: schemas.DataExportBatchUpdate
 */
export const ZDataExportBatchUpdateSchema = schemas.DataExportBatchUpdate;
export type DataExportBatchUpdate = z.infer<typeof ZDataExportBatchUpdateSchema>;
