/**
 * Patient handlers
 *
 * Generated by Handler Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./list-patients.handler.js";
export * from "./create-patient.handler.js";
export * from "./get-patient.handler.js";
export * from "./update-patient.handler.js";
export * from "./delete-patient.handler.js";
