/**
 * Routes for carePathwayTemplateOrderSetTemplates
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import { extractOrgId } from "../extract-org-id.js";
import type { Dependencies } from "../dependencies/workflow-care-pathways.dependencies.js";
import { listCarePathwayTemplateOrderSetTemplates } from "@cuur-cde/core/workflow-care-pathways/handlers/index.js";
export async function carePathwayTemplateOrderSetTemplatesRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /care-pathway-templates/{id}/order-set-templates
  fastify.get("/care-pathway-templates/:id/order-set-templates", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listCarePathwayTemplateOrderSetTemplates(deps.carePathwayTemplateOrderSetTemplateRepo, orgId);
    return reply.code(200).send(result);
  });

}
