/**
 * Routes for workQueues
 *
 * Generated by Service Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance } from "fastify";
import type { Dependencies } from "../dependencies/workflow-care-pathways.dependencies.js";
import { createWorkQueue, deleteWorkQueue, getWorkQueue, listWorkQueues, updateWorkQueue } from "@cuur-cde/core/workflow-care-pathways/handlers/index.js";
import type { WorkQueueInput, WorkQueueUpdate } from "@cuur-cde/core/workflow-care-pathways/types/index.js";
import { extractOrgId } from "../extract-org-id.js";
export async function workQueuesRoutes(
  fastify: FastifyInstance,
  deps: Dependencies
) {
  // GET /work-queues
  fastify.get("/work-queues", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await listWorkQueues(deps.workQueueRepo, orgId, request.query || {});
    return reply.code(200).send(result);
  });
  // POST /work-queues
  fastify.post("/work-queues", async (request, reply) => {
    const orgId = extractOrgId(request);
    const result = await createWorkQueue(deps.workQueueRepo, orgId, request.body as WorkQueueInput);
    return reply.code(201).send(result);
  });
  // GET /work-queues/{id}
  fastify.get("/work-queues/:id", async (request, reply) => {
    const orgId = extractOrgId(request);
        const id = (request.params as any).id;
    const result = await getWorkQueue(deps.workQueueRepo, orgId, id);
    return reply.code(200).send(result);
  });
  // PATCH /work-queues/{id}
  fastify.patch("/work-queues/:id", async (request, reply) => {
    const orgId = extractOrgId(request);
        const id = (request.params as any).id;
    const result = await updateWorkQueue(deps.workQueueRepo, orgId, id, request.body as WorkQueueUpdate);
    return reply.code(200).send(result);
  });
  // DELETE /work-queues/{id}
  fastify.delete("/work-queues/:id", async (request, reply) => {
    const orgId = extractOrgId(request);
        const id = (request.params as any).id;
        await deleteWorkQueue(deps.workQueueRepo, orgId, id);
    return reply.code(204).send();
  });

}
