/**
 * PatientClinicalData Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: patient-clinical-data
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ListPatientVitalParams, ZListPatientVitalParamsSchema } from "@cuur-cde/core/patient-clinical-data/models/patient-vital/index.js";
import { z } from "zod";

export function createListPatientVitalParams(overrides: Partial<ListPatientVitalParams> = {}) {
  const raw = {
    // No fields generated
    ...overrides,
  };

  return ZListPatientVitalParamsSchema.parse(raw);
}
