/**
 * Guideline Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas";

/**
 * Entity: GuidelineEntity
 * Description: Represents the Guideline domain model.
 * Source: schemas.Guideline
 */
export const ZGuidelineEntitySchema = schemas.Guideline as ZodType<any, any, any>;
export type GuidelineEntity = z.infer<typeof ZGuidelineEntitySchema>;
