/**
 * EvidenceCitation Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodType } from "zod";
import { schemas } from "../../../schemas/knowledge-evidence.schemas";

/**
 * Entity: EvidenceCitationEntity
 * Description: Represents the EvidenceCitation domain model.
 * Source: schemas.EvidenceCitation
 */
export const ZEvidenceCitationEntitySchema = schemas.EvidenceCitation as ZodType<any, any, any>;
export type EvidenceCitationEntity = z.infer<typeof ZEvidenceCitationEntitySchema>;
