/**
 * KnowledgeEvidence Domain Factories
 *
 * Generated by Test Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: knowledge-evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */



import { faker } from "@faker-js/faker";
import { ValueSetInput } from "@cuur-cde/core/knowledge-evidence";
import { knowledgeevidenceSchemas as schemas } from "@cuur-cde/core/knowledge-evidence/index.js";
import { z } from "zod";

export function createValueSetInput(overrides: Partial<ValueSetInput> = {}) {
  const raw = {
    category: overrides.category ?? faker.string.alpha(10),
    description: overrides.description ?? faker.string.alpha(10),
    metadata: overrides.metadata ?? {},
    name: overrides.name ?? faker.word.noun(),
    version: overrides.version ?? faker.string.alpha(10),
    ...overrides,
  };

  return schemas.ValueSetInput.parse(raw);
}
