/**
 * DataImportBatch Entity
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z, type ZodTypeAny } from "zod";
import { schemas } from "../../../schemas/integration-interoperability.schemas.js";

/**
 * Entity: DataImportBatchEntity
 * Description: Represents the DataImportBatch domain model.
 * Source: schemas.DataImportBatch
 */
export const ZDataImportBatchEntitySchema = schemas.DataImportBatch as ZodTypeAny;
export type DataImportBatchEntity = z.infer<typeof ZDataImportBatchEntitySchema>;
