/**
 * Repository interface for APIClientUsageMetric
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  APIClientUsageMetric
} from "../types/index.js";
/**
 * APIClientUsageMetricRepository Interface
 */
export interface APIClientUsageMetricRepository extends ReadRepository<APIClientUsageMetric, string, Record<string, never>> {

}
