/**
 * Repository interface for APICredential
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "@cuur-cde/core/_shared";

import type {
  APICredential,
  ListAPICredentialsParams,
  UpdateAPICredentialRequest
} from "@cuur-cde/core/integration-interoperability";
/**
 * APICredentialRepository Interface
 */
export interface APICredentialRepository extends CrudRepository<APICredential, APICredential, UpdateAPICredentialRequest, string, ListAPICredentialsParams> {

}
