/**
 * Repository interface for Connection
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CrudRepository,
} from "../../../_shared/src/repositories/_base-repository.js";

import type {
  Connection,
  ListConnectionsParams,
  UpdateConnectionRequest
} from "../types/index.js";
/**
 * ConnectionRepository Interface
 */
export interface ConnectionRepository extends CrudRepository<Connection, Connection, UpdateConnectionRequest, string, ListConnectionsParams> {

}
