/**
 * Repository interface for DataExportBatchFile
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "@cuur-cde/core/_shared";

import type {
  DataExportBatchFile
} from "@cuur-cde/core/integration-interoperability";
/**
 * DataExportBatchFileRepository Interface
 */
export interface DataExportBatchFileRepository extends ReadRepository<DataExportBatchFile, string, Record<string, never>> {

}
