/**
 * Repository interface for DataImportBatchRecord
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  DataImportBatchRecord
} from "../types/index.js";
/**
 * DataImportBatchRecordRepository Interface
 */
export interface DataImportBatchRecordRepository extends ReadRepository<DataImportBatchRecord, string, Record<string, never>> {

}
