/**
 * Repository interface for ExternalSystemConnection
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../../_shared/src/repositories/_base-repository.js";

import type {
  ExternalSystemConnection
} from "../types/index.js";
/**
 * ExternalSystemConnectionRepository Interface
 */
export interface ExternalSystemConnectionRepository extends ReadRepository<ExternalSystemConnection, string, Record<string, never>> {

}
