/**
 * Repository interface for HL7Message
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateDeleteReadRepository,
} from "../../../_shared/src/repositories/_base-repository.js";

import type {
  HL7Message,
  ListHLMessagesParams
} from "../types/index.js";
/**
 * HL7MessageRepository Interface
 */
export interface HL7MessageRepository extends CreateDeleteReadRepository<HL7Message, HL7Message, string, ListHLMessagesParams> {

}
