/**
 * Repository interface for IntegrationRunLog
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../shared/repositories/_base-repository.js";

import type {
  IntegrationRunLog
} from "../types/index.js";
/**
 * IntegrationRunLogRepository Interface
 */
export interface IntegrationRunLogRepository extends ReadRepository<IntegrationRunLog, string, Record<string, never>> {

}
