/**
 * Repository interface for InterfaceHealthCheck
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { CreateReadRepository } from "@cuur-cde/core/_shared";

import type {
  InterfaceHealthCheck,
  InterfaceHealthCheckInput,
  ListInterfaceHealthChecksParams,
} from "@cuur-cde/core/integration-interoperability";
/**
 * InterfaceHealthCheckRepository Interface
 */
export interface InterfaceHealthCheckRepository
  extends CreateReadRepository<
    InterfaceHealthCheck,
    InterfaceHealthCheckInput,
    string,
    ListInterfaceHealthChecksParams
  > {}
