/**
 * Repository interface for InterfaceHealthCheck
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: integration-interoperability
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { CreateReadRepository } from "../../../_shared/src/repositories/_base-repository.js";

import type {
  InterfaceHealthCheck,
  InterfaceHealthCheckInput,
  ListInterfaceHealthChecksParams,
} from "../types/index.js";
/**
 * InterfaceHealthCheckRepository Interface
 */
export interface InterfaceHealthCheckRepository
  extends CreateReadRepository<
    InterfaceHealthCheck,
    InterfaceHealthCheckInput,
    string,
    ListInterfaceHealthChecksParams
  > {}
