/**
 * Delete EscalationPolicy DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";

/**
 * DTO: DeleteEscalationPolicy DTO
 */
export const ZDeleteEscalationPolicySchema = z.object({});
export type DeleteEscalationPolicy = z.infer<typeof ZDeleteEscalationPolicySchema>;
