/**
 * TaskAssignment schemas
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: workflow-care-pathways
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

// Auto-generated barrel export
export * from "./entity/task-assignment.entity.js";
export * from "./dto/list-task-assignment.dto.js";
export * from "./dto/get-task-assignment.dto.js";
export * from "./dto/delete-task-assignment.dto.js";
