/**
 * List ExplanationFeature DTO
 *
 * Generated by Schema Generator v1.0.0
 * Generator Version: 1.0.0
 * Domain: decision-intelligence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { z } from "zod";
/**
 * DTO: ListExplanationFeatureParams
 * Direction: Query Parameters → Handler → Domain
 * Route: GET /explanation-feature
 */
export const ZListExplanationFeatureParamsSchema = z.object({

});

export type ListExplanationFeatureParams = z.infer<typeof ZListExplanationFeatureParamsSchema>;
